headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\demar\\Documents\\Claude_Twisted Growers\\app\\web\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install --include=dev --no-audit --no-fund && cd ../.. && npm install --include=dev --no-audit --no-fund && npm run check && cd app/web && npm run build"
base = "C:\\Users\\demar\\Documents\\Claude_Twisted Growers\\app\\web"

[build.environment]
NODE_VERSION = "22"
SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]