-- ============================================================================
-- v_room_contents — the seed-to-sale location mirror
--
-- Owner requirement, 7 Aug 2026: "you must mirror rooms as metrc has due to seed to sale we must
-- see and know where all inventory is."
--
-- Every Metrc location, keyed on (licence, name), showing living plants, unpackaged harvest
-- material AND packages — because inventory moves plants -> harvest -> packages through different
-- rooms, and a package-only view cannot answer "where is all inventory".
--
-- ── THE INSTRUCTION CAUGHT A REAL ERROR I WAS ABOUT TO SHIP ──────────────────
--
-- My first version normalised location names, collapsing "Pre-Trim Storage" into "Pre Trim
-- Storage Room" as a Metrc data problem. TWO things were wrong with that.
--
-- 1. It broke rule D2. Metrc is the legal record and this is a read-only mirror; papering over a
--    Metrc value inside the platform hides it from the state record. That is the rule verbatim.
--
-- 2. THE DUPLICATE WAS NOT A DUPLICATE. Keyed on licence, the answer changes completely:
--        MC281714  "Pre Trim Storage Room"   72 packages, 6 open harvests, 756.9 lb unpackaged
--        MP281909  "Pre-Trim Storage"        61 packages, 494.9 lb packaged
--    Two DIFFERENT rooms under two DIFFERENT licences. Nothing to correct at source.
--
-- And the same is true of four more names that exist under BOTH licences with different contents:
--        Fulfillment Vault   MC 1,222 packages + 16 open harvests   |  MP 394 packages
--        Finish Vault        MC   171 packages                      |  MP 516 packages
--        Freezer/Biomass     MC   101 packages                      |  MP 166 packages
--        Packaging Room      MC     2 packages                      |  MP  81 packages
--
-- So a view keyed on location NAME ALONE silently sums two legally distinct places. For
-- seed-to-sale that is exactly the error the owner's instruction was guarding against.
--
-- ── PLACEMENT IS COMPLETE, which is the good news ────────────────────────────
--    0 packages with no location
--    0 packages in a location absent from metrc_locations
--   15,595 plants all placed: Flower Room #1 4,828 · #2 2,665 · #3 3,903 · #4 4,069 ·
--   Mother Room 130. That total cross-checks against the "Plants mirrored 15,595" tile.
--   38 Metrc locations; 25 hold something; the rest are shown as EMPTY rather than omitted, so
--   an empty room is visibly empty instead of missing.
--
-- ── CONFIRMED BUSINESS FACT, owner 7 Aug 2026 ────────────────────────────────
-- "Twisted Growers LLC" appearing as a THIRD-PARTY SUPPLIER is CORRECT, not a fault. The company
-- holds two licences — cultivation MC281714 and manufacturing MP281909 — so material moving
-- between them genuinely has a different origin licence from the one holding it. Anything
-- reporting third-party material must say so, or it reads as an error every time.
-- Belongs in the LOCKED FACTS section of CLAUDE.md.
--
-- ── NEVER SUM THESE ──────────────────────────────────────────────────────────
-- unpackaged_harvest_lb is material not yet packaged; packaged_lb is finished packages. Adding
-- them mixes pre- and post-packaging states, the same class of error as mixing wet and dry.
-- ============================================================================

-- ============================================================================
-- REVISION 2 — I broke rule B4 and shipped it. Corrected.
--
-- still_in_room_lb is NOT material sitting in a room. It is wet minus packaged minus waste - an
-- ARITHMETIC RESIDUAL on a WET basis, still containing the water yet to evaporate. Proof: on the
-- 350 CLOSED harvests it totals 24,896.6 lb, and wet - packaged - waste = 24,896.6. A closed
-- harvest has nothing physically left in the room, so that figure is evaporated water.
--
-- My first version reported it as "unpackaged harvest material" in pounds, beside dry packaged
-- pounds. That is rule B4 - the error HANDOFF.md records as having once overstated open harvests
-- by 3,800 lb. I quoted that rule the same morning and then made it.
--
-- Scale of my error, open harvests:
--     reported as unpackaged material   4,514.8 lb   (WET)
--     dry equivalent at the 70-77% band 1,038 - 1,354 lb
--     overstated by roughly 3.8x
--
-- Now: unpackaged_WET_lb is named for what it is, with unpackaged_dry_equiv_low/high beside it
-- for any comparison. Per room, e.g. Fulfillment Vault MC281714: 2,059.7 lb WET = 474-618 lb dry
-- equivalent, against 192.2 lb already packaged.
--
-- ── THE MASS BALANCE, and why it is a DEFINITION that blocks it, not data ────
-- 350 closed harvests: 39,853.3 lb wet in · 11,289.3 lb packaged · 3,667.4 lb waste.
--     TEST A  loss excluding waste          = 71.7%  INSIDE the owner-set 70-77% band -> closes
--     TEST B  evaporation, waste taken out  = 62.5%  BELOW the 70% floor -> does not close
-- The two differ by exactly the 3,667.4 lb of waste, and nothing defines whether the band
-- includes it. Agent A independently arrived at 62.5% and recorded D1 as closed on that basis.
--
-- So the honest position: the mass balance closes on one reading and not the other, and the
-- question is a definition the owner must settle - does "expected moisture loss 70-77%" mean
-- weight lost to evaporation ONLY, or all weight not packaged including waste? Choosing one
-- silently would decide a 3,667 lb question by assumption. Rule A5.
-- ============================================================================
