import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

export async function permissionMatrixFixture(query) {
  await query(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.user_id',true),'')::uuid$$;
    create function public.f_caller_is_admin() returns boolean language sql stable as $$select coalesce(current_setting('test.admin',true)='yes',false)$$;
    grant usage on schema auth to authenticated;
    create table app_roles(role text primary key,label text,rank integer);
    create table app_users(user_id uuid primary key);
    create table nav_registry(id integer primary key,view_key text unique,enabled boolean,category_order integer,item_order integer);
    create table page_permissions(id uuid primary key default gen_random_uuid(),role text,view_key text,can_view boolean,can_edit boolean,can_approve boolean,can_export boolean,can_delete boolean,updated_by uuid,updated_at timestamptz,unique(role,view_key));
    create table nav_role_visibility(view_key text,role text,visible boolean,updated_at timestamptz,primary key(view_key,role));
    grant select on app_roles,app_users,nav_registry to authenticated;
    grant select,insert,update on page_permissions,nav_role_visibility to authenticated;
    alter table page_permissions enable row level security;
    alter table nav_role_visibility enable row level security;
    create policy page_read on page_permissions for select to authenticated using(true);
    create policy page_write on page_permissions for all to authenticated using(f_caller_is_admin()) with check(f_caller_is_admin());
    create policy nav_read on nav_role_visibility for select to authenticated using(true);
    create policy nrv_write on nav_role_visibility for all to authenticated using(false) with check(false);
    insert into app_roles values('staff','Staff',1);
    insert into nav_registry values(1,'alpha',true,1,1),(2,'beta',true,1,2);
    create publication supabase_realtime;
  `);
  const sql = readFileSync(new URL('../../supabase/migrations/20260912160141_gpt_atomic_permission_matrix.sql', import.meta.url), 'utf8');
  await query('begin'); await query(sql); await query('commit');
  assert.equal((await query(`select count(*)::int as n from pg_publication_tables where pubname='supabase_realtime'`)).rows[0].n,4);
  await query(`set role authenticated; set test.user_id='11111111-1111-4111-8111-111111111111'; set test.admin='yes';`);
  const read = async () => (await query(`select f_permission_matrix('staff') as result`)).rows[0].result;
  const initial = await read();
  const page = key => ({ view_key:key,menu:true,can_view:true,can_edit:false,can_approve:false,can_export:false,can_delete:false });
  const save = (revision,pages) => query(`select f_save_permission_matrix('staff','${revision}','${JSON.stringify(pages)}'::jsonb) as result`);
  const saved = (await save(initial.revision,[page('alpha'),page('beta')])).rows[0].result;
  assert.equal(saved.saved_count,2);
  assert.ok(saved.permissions.every(p=>p.can_view));
  assert.ok(saved.visibility.every(p=>p.visible));
  await assert.rejects(save(initial.revision,[page('alpha')]),/changed after/i);
  await assert.rejects(save(saved.revision,[]),/No permission changes/i);
  await assert.rejects(save(saved.revision,[page('alpha'),page('alpha')]),/Duplicate/i);
  await assert.rejects(save(saved.revision,[{...page('alpha'),can_view:null}]),/explicit boolean/i);
  await assert.rejects(save(saved.revision,[page('unknown')]),/registered/i);
  await assert.rejects(save(saved.revision,[{...page('alpha'),can_view:false}]),/visible menu requires/i);
  await query(`set test.admin='no'`);
  assert.equal((await read()).revision,saved.revision);
  await assert.rejects(save(saved.revision,[page('alpha')]),/admin settings capability/i);
  await query(`set test.admin='yes'; reset role;`);
  await query(`create function reject_beta() returns trigger language plpgsql as $$begin if new.view_key='beta' then raise exception 'fixture refuses second table'; end if; return new; end$$;
    create trigger refuse_second_table before update on nav_role_visibility for each row execute function reject_beta();
    set role authenticated;`);
  await assert.rejects(save(saved.revision,[{...page('alpha'),menu:false,can_view:false},page('beta')]),/fixture refuses second table/i);
  assert.equal((await read()).revision,saved.revision,'Both tables must roll back when the second write fails');
  await query('reset role; set role anon;');
  await assert.rejects(read(),/permission denied/i);
  await assert.rejects(save(saved.revision,[page('alpha')]),/permission denied/i);
  await query('reset role;');
  return {revision:saved.revision,pages:[page('alpha')]};
}
