// ForensicCallouts.jsx — Plan B: CHRO-grade callout forensics.
// One row per callout/no-show/late with coverage, excused, PTO, short-staffed,
// pattern count, and disciplinary linkage. Fully filterable + printable.
import { useState, useEffect, useCallback, useMemo } from 'react'
import { useScope } from '../lib/scope.jsx'
import { forensicCallouts } from '../lib/supabase'
import { companyName } from '../lib/config.js'

const esc = (s) => String(s ?? '').replace(/[&<>"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]))
const fmtDate = (s) => s ? new Date(s + (String(s).length === 10 ? 'T00:00:00' : '')).toLocaleDateString('en-US', { month:'short', day:'numeric', year:'numeric' }) : '—'
const fmtTime = (s) => s ? new Date(s).toLocaleString('en-US', { month:'short', day:'numeric', hour:'2-digit', minute:'2-digit' }) : '—'
const iso = (d) => d.toISOString().slice(0, 10)

function buildPrint({ rows, from, to, summary }) {
  const printedAt = new Date().toLocaleString('en-US', { dateStyle:'long', timeStyle:'short' })
  const body = rows.map(r => `<tr>
    <td>${esc(fmtDate(r.callout_date))}</td><td>${esc(r.shift_slot || '—')}</td>
    <td>${esc(r.employee)}</td><td>${esc(r.node)}</td>
    <td class="${r.exception_type === 'no_show' ? 'bad' : ''}">${esc(r.exception_type)}</td>
    <td>${esc(r.reason || '—')}</td>
    <td>${r.covered ? 'Yes — ' + esc(r.covered_by || '') : '<span class="bad">No</span>'}</td>
    <td>${r.short_staffed ? '<span class="bad">Yes</span>' : 'No'}</td>
    <td>${r.excused === true ? 'Excused' : r.excused === false ? 'Unexcused' : '—'}</td>
    <td>${r.pto_used ? 'Yes' : 'No'}</td>
    <td>${r.disciplinary_count > 0 ? esc(String(r.disciplinary_count)) : '—'}</td>
  </tr>`).join('')
  return `<!doctype html><html><head><meta charset="utf-8"><title>Attendance Forensic Report</title><style>
    body{font-family:Georgia,serif;color:#111;margin:0;padding:30px;font-size:11px}
    .lh{display:flex;justify-content:space-between;border-bottom:3px double #111;padding-bottom:8px;margin-bottom:12px}
    .co{font-size:13px;font-weight:bold} h1{font-size:17px;margin:2px 0}
    .sum{background:#f4f4f0;border:1px solid #bbb;padding:8px 12px;margin:10px 0;font-size:11px}
    table{width:100%;border-collapse:collapse;margin-top:6px} th,td{border:1px solid #999;padding:3px 5px;text-align:left;font-size:10px}
    th{background:#eee;text-transform:uppercase;font-size:8px} .bad{color:#a01024;font-weight:bold}
    .foot{margin-top:14px;border-top:1px solid #ccc;padding-top:5px;font-size:9px;color:#777}
    @media print{body{padding:0}}
  </style></head><body>
    <div class="lh"><div><div class="co">{companyName()}</div>
      <h1>Attendance Forensic Report</h1><div>Period: ${esc(from || 'all')} → ${esc(to || 'all')}</div></div>
      <div style="text-align:right;font-size:10px">Printed: ${esc(printedAt)}<br/>Confidential — HR/Legal</div></div>
    <div class="sum"><b>Summary:</b> ${summary.total} events · ${summary.uncovered} uncovered ·
      ${summary.shortStaffed} left short-staffed · ${summary.noShows} no-shows · ${summary.withDisc} with prior discipline</div>
    <table><thead><tr><th>Date</th><th>Slot</th><th>Employee</th><th>Location</th><th>Type</th><th>Reason</th>
      <th>Covered</th><th>Short?</th><th>Excused</th><th>PTO</th><th>Disc.</th></tr></thead><tbody>${body}</tbody></table>
    <div class="foot">Generated by {companyName()} HR · Confidential attendance record for HR/legal use. Data sourced live from shift exceptions, coverage, time-off, attendance patterns, and disciplinary records.</div>
  </body></html>`
}
function printDoc(html) {
  const w = window.open('', '_blank', 'width=1000,height=720')
  if (!w) { alert('Please allow pop-ups to print.'); return }
  w.document.write(html); w.document.close(); w.focus(); setTimeout(() => { try { w.print() } catch (e) {} }, 350)
}

const FILTERS = [
  { key: 'uncovered',  label: 'Uncovered' },
  { key: 'short',      label: 'Short-staffed' },
  { key: 'noshow',     label: 'No-shows' },
  { key: 'disc',       label: 'Has discipline' },
  { key: 'pattern',    label: 'Has pattern' },
  { key: 'pto',        label: 'Used PTO' },
  { key: 'unexcused',  label: 'Unexcused' },
]

export default function ForensicCallouts() {
  const { locationIds } = useScope()
  const today = new Date()
  const ago = new Date(Date.now()); ago.setDate(ago.getDate() - 90)
  const [from, setFrom] = useState(iso(ago))
  const [to, setTo] = useState(iso(today))
  const [rows, setRows] = useState([])
  const [loading, setLoading] = useState(false)
  const [err, setErr] = useState(null)
  const [active, setActive] = useState({})   // active filters
  const [q, setQ] = useState('')

  const load = useCallback(async () => {
    if (!locationIds || locationIds.length === 0) { setRows([]); return }
    setLoading(true); setErr(null)
    try {
      const res = await forensicCallouts(locationIds, from || null, to || null)
      setRows(Array.isArray(res?.callouts) ? res.callouts : [])
    } catch (e) { setErr(e.message) } finally { setLoading(false) }
  }, [locationIds, from, to])
  useEffect(() => { load() }, [load])

  const filtered = useMemo(() => rows.filter(r => {
    if (q && !(`${r.employee} ${r.node} ${r.reason || ''}`.toLowerCase().includes(q.toLowerCase()))) return false
    if (active.uncovered && r.covered) return false
    if (active.short && !r.short_staffed) return false
    if (active.noshow && r.exception_type !== 'no_show') return false
    if (active.disc && !(r.disciplinary_count > 0)) return false
    if (active.pattern && !(r.pattern_count > 0)) return false
    if (active.pto && !r.pto_used) return false
    if (active.unexcused && r.excused !== false) return false
    return true
  }), [rows, active, q])

  const summary = useMemo(() => ({
    total: filtered.length,
    uncovered: filtered.filter(r => !r.covered).length,
    shortStaffed: filtered.filter(r => r.short_staffed).length,
    noShows: filtered.filter(r => r.exception_type === 'no_show').length,
    withDisc: filtered.filter(r => r.disciplinary_count > 0).length,
  }), [filtered])

  const cardS = { background:'var(--t-surface)', border:'1px solid var(--t-line)', borderRadius:0, padding:12 }
  const ip = { padding:'5px 8px', background:'var(--t-surface)', color:'var(--t-text)', border:'1px solid var(--t-line)', borderRadius:0, fontSize:12 }
  const KTile = ({ label, value, color }) => (
    <div style={{ ...cardS, textAlign:'center' }}>
      <div style={{ fontSize:9, fontWeight:800, letterSpacing:'.08em', color:'var(--t-text-muted)', textTransform:'uppercase' }}>{label}</div>
      <div style={{ fontSize:22, fontWeight:800, color: color || 'var(--t-text)', marginTop:3 }}>{value}</div>
    </div>
  )

  return (
    <div style={{ color:'var(--t-text)', fontSize:13 }}>
      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:12, flexWrap:'wrap', gap:8 }}>
        <div style={{ fontSize:16, fontWeight:800, letterSpacing:'-.3px' }}>ATTENDANCE FORENSICS — CALLOUTS</div>
        <div style={{ display:'flex', gap:6, alignItems:'center', flexWrap:'wrap' }}>
          <input type="date" value={from} onChange={e => setFrom(e.target.value)} style={ip} />
          <span style={{ color:'var(--t-text-muted)' }}>→</span>
          <input type="date" value={to} onChange={e => setTo(e.target.value)} style={ip} />
          <button onClick={load} style={{ ...ip, fontWeight:700, cursor:'pointer', color:'var(--t-text-muted)' }}>REFRESH</button>
          <button onClick={() => printDoc(buildPrint({ rows: filtered, from, to, summary }))}
            style={{ ...ip, fontWeight:700, cursor:'pointer', background:'var(--t-accent)', color:'var(--t-on-grad)', border:'1px solid var(--t-accent)' }}>🖨 PRINT REPORT</button>
        </div>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'repeat(5,1fr)', gap:8, marginBottom:12 }}>
        <KTile label="Events" value={summary.total} />
        <KTile label="Uncovered" value={summary.uncovered} color={summary.uncovered ? 'var(--t-danger)' : 'var(--t-success)'} />
        <KTile label="Left Short" value={summary.shortStaffed} color={summary.shortStaffed ? 'var(--t-warn)' : 'var(--t-text)'} />
        <KTile label="No-Shows" value={summary.noShows} color={summary.noShows ? 'var(--t-danger)' : 'var(--t-text)'} />
        <KTile label="W/ Discipline" value={summary.withDisc} color={summary.withDisc ? 'var(--t-warn)' : 'var(--t-text)'} />
      </div>

      <div style={{ ...cardS, marginBottom:12, display:'flex', gap:8, alignItems:'center', flexWrap:'wrap' }}>
        <input placeholder="Search employee / reason…" value={q} onChange={e => setQ(e.target.value)} style={{ ...ip, flex:'1 1 200px' }} />
        {FILTERS.map(f => {
          const on = !!active[f.key]
          return (
            <button key={f.key} onClick={() => setActive(a => ({ ...a, [f.key]: !a[f.key] }))}
              style={{ ...ip, cursor:'pointer', fontWeight:700, fontSize:11,
                background: on ? 'var(--t-accent)' : 'var(--t-surface)', color: on ? 'var(--t-on-grad)' : 'var(--t-text-muted)',
                border: `1px solid ${on ? 'var(--t-accent)' : 'var(--t-line)'}` }}>{f.label}</button>
          )
        })}
      </div>

      {err && <div style={{ ...cardS, borderColor:'var(--t-danger)', color:'var(--t-danger)', marginBottom:10 }}>{err}</div>}

      <div style={{ ...cardS, padding:0, overflowX:'auto' }}>
        <table style={{ width:'100%', borderCollapse:'collapse', fontSize:12 }}>
          <thead>
            <tr style={{ background:'var(--t-surface-2)' }}>
              {['Date','Slot','Employee','Location','Type','Reason','Covered by','Short?','Excused','PTO','Pattern','Disc.'].map(h => (
                <th key={h} style={{ textAlign:'left', padding:'8px 10px', fontSize:9, fontWeight:800, letterSpacing:'.05em', color:'var(--t-text-muted)', textTransform:'uppercase', borderBottom:'1px solid var(--t-line)', whiteSpace:'nowrap' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={12} style={{ padding:24, textAlign:'center', color:'var(--t-accent)' }}>Loading…</td></tr>
            ) : filtered.length === 0 ? (
              <tr><td colSpan={12} style={{ padding:24, textAlign:'center', color:'var(--t-text-faint)' }}>No callouts match these filters for this period.</td></tr>
            ) : filtered.map(r => (
              <tr key={r.exception_id} style={{ borderBottom:'1px solid var(--t-line)' }}>
                <td style={{ padding:'7px 10px', whiteSpace:'nowrap' }}>{fmtDate(r.callout_date)}</td>
                <td style={{ padding:'7px 10px' }}>{r.shift_slot || '—'}</td>
                <td style={{ padding:'7px 10px', fontWeight:600 }}>{r.employee}</td>
                <td style={{ padding:'7px 10px', color:'var(--t-text-muted)' }}>{r.node}</td>
                <td style={{ padding:'7px 10px' }}>
                  <span style={{ fontSize:10, fontWeight:800, padding:'2px 6px', color: r.exception_type === 'no_show' ? 'var(--t-danger)' : r.exception_type === 'late' ? 'var(--t-warn)' : 'var(--t-text-muted)', border:`1px solid ${r.exception_type === 'no_show' ? 'var(--t-danger)' : 'var(--t-line)'}` }}>{(r.exception_type || '').toUpperCase()}</span>
                </td>
                <td style={{ padding:'7px 10px', maxWidth:180, color:'var(--t-text-muted)' }}>{r.reason || '—'}</td>
                <td style={{ padding:'7px 10px', color: r.covered ? 'var(--t-success)' : 'var(--t-danger)', fontWeight:600 }}>{r.covered ? (r.covered_by || 'Yes') : 'NOT COVERED'}</td>
                <td style={{ padding:'7px 10px', color: r.short_staffed ? 'var(--t-warn)' : 'var(--t-text-faint)', fontWeight:700 }}>{r.short_staffed ? 'YES' : 'no'}</td>
                <td style={{ padding:'7px 10px' }}>{r.excused === true ? 'Excused' : r.excused === false ? <span style={{ color:'var(--t-warn)' }}>Unexcused</span> : '—'}</td>
                <td style={{ padding:'7px 10px' }}>{r.pto_used ? 'Yes' : 'no'}</td>
                <td style={{ padding:'7px 10px', color: r.pattern_count > 0 ? 'var(--t-danger)' : 'var(--t-text-faint)', fontWeight:700 }}>{r.pattern_count || '—'}</td>
                <td style={{ padding:'7px 10px', fontWeight:700, color: r.disciplinary_count > 0 ? 'var(--t-warn)' : 'var(--t-text-faint)' }}>{r.disciplinary_count > 0 ? `${r.disciplinary_count} ▸` : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
