#!/usr/bin/env node
/* PHASE 0 — make the schema reproducible.
 *
 * THE PROBLEM THIS SOLVES. The repository holds 6 migration files describing 4 tables. The live
 * database holds 229 tables, 225 views, 514 RLS policies and 30 cron jobs. So the schema exists
 * in exactly ONE place: production, of a licensed business.
 *
 * That is the real blocker under "no staging environment". Docker is incidental — even a paid
 * Supabase branch seeds from migration history, so it would come up nearly empty too. Nothing can
 * be tested anywhere else until the schema can be rebuilt from the repo.
 *
 * WHY THIS EXISTS RATHER THAN `supabase db dump`. That command needs Docker, and Docker Desktop on
 * this machine fails to start on stale socket reparse points that Windows cannot delete. This
 * needs only the pg driver, so recoverability no longer depends on a container runtime starting.
 *
 * WHAT IT WRITES. supabase/migrations/<timestamp>_baseline_live_schema.sql containing, in
 * dependency order: extensions, enums, tables, constraints, indexes, functions, views,
 * materialized views, RLS enablement, policies, grants and cron jobs.
 *
 * IT IS READ-ONLY. It only ever SELECTs from catalogues. It cannot modify the database.
 *
 * CREDENTIALS. Read from .mcp.json (gitignored) or PGURL. Never printed, never written into the
 * output file.
 *
 *   node tools/checks/dump-schema.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

function connectionString() {
  if (process.env.PGURL) return process.env.PGURL;
  const p = join(ROOT, ".mcp.json");
  if (!existsSync(p)) {
    console.error("No PGURL set and no .mcp.json found. Cannot connect.");
    process.exit(1);
  }
  const cfg = JSON.parse(readFileSync(p, "utf8"));
  const url = cfg?.mcpServers?.["twisted-growers"]?.args?.[0];
  if (!url) { console.error("No connection string in .mcp.json"); process.exit(1); }
  /* pg 8.22+ treats sslmode=require as verify-full, and Supabase's pooler certificate is not in
     the default Node trust store, so a plain 'require' fails with "self-signed certificate in
     certificate chain". uselibpqcompat restores libpq semantics: the connection is still
     ENCRYPTED, the certificate chain simply is not verified. Acceptable for a read-only dump to
     a known host; not a pattern to copy into anything that writes. */
  return url.replace(/sslmode=[a-z-]+/, "uselibpqcompat=true&sslmode=require");
}

const q = async (c, sql, params) => (await c.query(sql, params)).rows;

const client = new pg.Client({
  connectionString: connectionString(),
  ssl: { rejectUnauthorized: false },
  statement_timeout: 120000,
});

const out = [];
const section = (t) => out.push(`\n-- ${"=".repeat(74)}\n-- ${t}\n-- ${"=".repeat(74)}\n`);

try {
  await client.connect();
  console.log("connected (read-only dump)");

  out.push("-- BASELINE SCHEMA, extracted from the live database.");
  out.push("-- Generated by tools/checks/dump-schema.mjs. Do not hand-edit.");
  out.push("-- This file exists so the schema can be rebuilt somewhere that is not production.");

  section("EXTENSIONS");
  for (const r of await q(client, `
    select 'create extension if not exists ' || quote_ident(extname) ||
           ' with schema ' || quote_ident(n.nspname) || ';' as ddl
    from pg_extension e join pg_namespace n on n.oid = e.extnamespace
    where extname <> 'plpgsql' order by extname`)) out.push(r.ddl);

  section("ENUM TYPES");
  for (const r of await q(client, `
    select 'create type public.' || quote_ident(t.typname) || ' as enum (' ||
           string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) || ');' as ddl
    from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    join pg_namespace n on n.oid = t.typnamespace and n.nspname = 'public'
    group by t.typname order by t.typname`)) out.push(r.ddl);

  section("TABLES");
  const tables = await q(client, `
    select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relkind='r' order by c.relname`);
  for (const { relname } of tables) {
    const cols = await q(client, `
      select column_name, data_type, udt_name, is_nullable, column_default,
             character_maximum_length, numeric_precision, numeric_scale
      from information_schema.columns
      where table_schema='public' and table_name=$1 order by ordinal_position`, [relname]);
    const defs = cols.map((c) => {
      let t = c.data_type === "USER-DEFINED" ? `public.${c.udt_name}`
            : c.data_type === "ARRAY" ? `${c.udt_name.replace(/^_/, "")}[]`
            : c.data_type === "character varying" && c.character_maximum_length
              ? `varchar(${c.character_maximum_length})`
            : c.data_type === "numeric" && c.numeric_precision
              ? `numeric(${c.numeric_precision},${c.numeric_scale ?? 0})`
            : c.data_type;
      let s = `  ${JSON.stringify(c.column_name).replace(/"/g, '"')} ${t}`;
      if (c.column_default) s += ` default ${c.column_default}`;
      if (c.is_nullable === "NO") s += " not null";
      return s;
    });
    out.push(`create table if not exists public.${relname} (\n${defs.join(",\n")}\n);`);
  }

  section("CONSTRAINTS — primary keys, uniques, foreign keys, checks");
  for (const r of await q(client, `
    select 'alter table public.' || quote_ident(rel.relname) ||
           ' add constraint ' || quote_ident(con.conname) || ' ' ||
           pg_get_constraintdef(con.oid) || ';' as ddl
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace n on n.oid = rel.relnamespace and n.nspname='public'
    order by case con.contype when 'p' then 1 when 'u' then 2 when 'f' then 3 else 4 end,
             rel.relname, con.conname`)) out.push(r.ddl);

  section("INDEXES");
  for (const r of await q(client, `
    select indexdef || ';' as ddl from pg_indexes
    where schemaname='public'
      and indexname not in (select conname from pg_constraint where contype in ('p','u'))
    order by tablename, indexname`)) out.push(r.ddl);

  section("FUNCTIONS");
  for (const r of await q(client, `
    select pg_get_functiondef(p.oid) || ';' as ddl
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public'
      and not exists (select 1 from pg_depend d
                      where d.objid=p.oid and d.classid='pg_proc'::regclass and d.deptype='e')
    order by p.proname`)) out.push(r.ddl);

  section("VIEWS — created in dependency order");
  for (const r of await q(client, `
    with recursive deps as (
      select c.oid, c.relname, 0 as depth
      from pg_class c join pg_namespace n on n.oid=c.relnamespace
      where n.nspname='public' and c.relkind in ('v','m')
      union all
      select c.oid, c.relname, d.depth+1
      from deps d
      join pg_depend dep on dep.refobjid = d.oid
      join pg_rewrite rw on rw.oid = dep.objid
      join pg_class c on c.oid = rw.ev_class and c.relkind in ('v','m')
      where d.depth < 12 and c.oid <> d.oid
    )
    select relname, max(depth) as depth from deps group by relname order by max(depth), relname`)) {
    const [{ kind }] = await q(client,
      `select relkind::text as kind from pg_class c join pg_namespace n on n.oid=c.relnamespace
       where n.nspname='public' and c.relname=$1`, [r.relname]);
    const [{ def }] = await q(client,
      `select pg_get_viewdef(('public.'||quote_ident($1))::regclass, true) as def`, [r.relname]);
    out.push(kind === "m"
      ? `create materialized view if not exists public.${r.relname} as\n${def}`
      : `create or replace view public.${r.relname} as\n${def}`);
  }

  section("ROW LEVEL SECURITY");
  for (const r of await q(client, `
    select 'alter table public.' || quote_ident(c.relname) ||
           ' enable row level security;' as ddl
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relkind='r' and c.relrowsecurity order by c.relname`)) out.push(r.ddl);

  section("POLICIES");
  for (const r of await q(client, `
    select 'create policy ' || quote_ident(p.polname) || ' on public.' || quote_ident(c.relname) ||
           ' as ' || case when p.polpermissive then 'permissive' else 'restrictive' end ||
           ' for ' || case p.polcmd when 'r' then 'select' when 'a' then 'insert'
                                    when 'w' then 'update' when 'd' then 'delete' else 'all' end ||
           ' to ' || coalesce((select string_agg(quote_ident(pg_get_userbyid(r)), ', ')
                               from unnest(p.polroles) r where r <> 0), 'public') ||
           coalesce(' using (' || pg_get_expr(p.polqual, p.polrelid) || ')', '') ||
           coalesce(' with check (' || pg_get_expr(p.polwithcheck, p.polrelid) || ')', '') || ';' as ddl
    from pg_policy p join pg_class c on c.oid=p.polrelid
    join pg_namespace n on n.oid=c.relnamespace and n.nspname='public'
    order by c.relname, p.polname`)) out.push(r.ddl);

  section("GRANTS — application roles only");
  for (const r of await q(client, `
    select 'grant ' || string_agg(distinct privilege_type, ', ') || ' on public.' ||
           quote_ident(table_name) || ' to ' || quote_ident(grantee) || ';' as ddl
    from information_schema.role_table_grants
    where table_schema='public' and grantee in ('anon','authenticated','service_role')
    group by table_name, grantee order by table_name, grantee`)) out.push(r.ddl);

  /* Optional sections. The dump must NOT fail wholesale because one part is inaccessible - a
     read-only role cannot see the cron schema, and losing 229 tables of DDL over that would be
     absurd. Each records why it is absent rather than leaving a silent gap (rule A3). */
  section("SCHEDULED JOBS — cron. Review before running anywhere but production.");
  let jobs = "not readable";
  try {
    const rows = await q(client, `
      select '-- select cron.schedule(' || quote_literal(coalesce(jobname,'job'||jobid)) || ', ' ||
             quote_literal(schedule) || ', ' || quote_literal(command) || ');' as ddl
      from cron.job order by jobid`);
    rows.forEach((r) => out.push(r.ddl));
    jobs = String(rows.length);
  } catch (e) {
    out.push(`-- NOT CAPTURED: ${e.message.trim()}`);
    out.push("-- The dumping role cannot read the cron schema. Re-run with a role that can, or");
    out.push("-- recreate schedules by hand. Absence recorded rather than left silent (rule A3).");
    console.warn("  cron jobs not captured:", e.message.trim());
  }

  const counts = (await q(client, `
    select (select count(*) from pg_tables where schemaname='public') tables,
           (select count(*) from pg_views  where schemaname='public') views,
           (select count(*) from pg_matviews where schemaname='public') matviews,
           (select count(*) from pg_policy p join pg_class c on c.oid=p.polrelid
            join pg_namespace n on n.oid=c.relnamespace where n.nspname='public') policies`))[0];
  counts.jobs = jobs;

  /* Record what was captured, machine-readably, so schema-baseline-fresh.mjs can compare this
     file against the live database instead of only checking its age. A baseline that merely
     LOOKS recent is not recoverability - on 8 Aug 2026 the age check passed at 22h old while
     production had moved 244 -> 260 tables and 539 -> 567 policies underneath it. */
  out.splice(3, 0,
    `-- BASELINE COUNTS: tables=${counts.tables} views=${counts.views} ` +
    `matviews=${counts.matviews} policies=${counts.policies}`);

  const ts = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  const dir = join(ROOT, "supabase", "migrations");
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `${ts}_baseline_live_schema.sql`);
  writeFileSync(file, out.join("\n") + "\n");

  console.log(`wrote ${file}`);
  console.log(`  ${counts.tables} tables · ${counts.views} views · ${counts.matviews} matviews`);
  console.log(`  ${counts.policies} policies · ${counts.jobs} cron jobs (commented out)`);
  console.log(`  ${(out.join("\n").length / 1024).toFixed(0)} KB`);
} catch (err) {
  console.error("dump failed:", err.message);
  process.exit(1);
} finally {
  await client.end().catch(() => {});
}
