#!/usr/bin/env node
/* secret-scan.mjs — a credential must never reach a file on disk.
 *
 * WHY THIS EXISTS
 *
 * ci.yml already runs gitleaks, but with `continue-on-error: true` — advisory — and it
 * scans COMMITS. Two gaps followed from that, and both were real:
 *
 *   1. On 8 Aug 2026, 23 permission entries carrying live credentials were found in
 *      `Desktop\Twisted Growers\.claude\settings.local.json`: 10 edge-function admin
 *      keys, 5 Supabase JWTs, 4 Netlify proxy tokens, 4 signed storage URLs. That file
 *      is in OneDrive, so it synced to the cloud. It was never committed, so a
 *      commit-scanner would never have seen it, and nothing else was looking.
 *
 *   2. A working database password did once reach a commit in .mcp.json and was pushed
 *      to main — which is why gitleaks was added. Advisory means it did not stop it.
 *
 * So this scans the WORKING TREE, fails the build, and exports its patterns so the
 * PreToolUse hook refuses to write a credential in the first place. One definition,
 * two enforcement points — and guard-fixtures.mjs proves they agree.
 *
 * DESIGN NOTE: patterns match credential SHAPES, not vocabulary. The 8 Aug lesson is
 * that a check firing on the word for a thing eventually fires on the documentation
 * explaining the thing. Every pattern below requires structure a real secret has and
 * prose does not — a JWT's three base64 segments, a URI with a password in it.
 */
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "../..");

/* Shared with tools/hooks/guard-secrets.mjs. Adding a pattern here arms both. */
export const SECRET_PATTERNS = [
  { name: "JSON Web Token",
    re: /\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/,
    fix: "Read it from the environment at run time. Never write a JWT into a file." },
  { name: "URI with an embedded password",
    re: /\b(postgres(ql)?|mysql|mongodb(\+srv)?|redis|amqp):\/\/[^\s:@/]+:[^\s:@/]+@/i,
    fix: "Use a connection string from the environment, or a .env file that is gitignored." },
  { name: "signed storage URL with a token",
    re: /storage\/v1\/object\/sign\/[^\s"']*[?&]token=/i,
    fix: "Signed links expire and are regenerated by cron. Fetch one, never store one." },
  { name: "private key block",
    re: /-----BEGIN[ A-Z]*PRIVATE KEY-----/,
    fix: "Private keys belong in a secret store, never in the repository." },
  { name: "AWS access key id",
    re: /\bAKIA[0-9A-Z]{16}\b/,
    fix: "Rotate it immediately and load from the environment." },
  { name: "GitHub token",
    re: /\bgh[pousr]_[A-Za-z0-9]{36,}\b/,
    fix: "Rotate it in GitHub settings and load from the environment." },
  { name: "Slack token",
    re: /\bxox[abprs]-[A-Za-z0-9-]{10,}\b/,
    fix: "Rotate in Slack and load from the environment." },
];

/* Files that legitimately describe credential shapes. Listed here WITH A REASON so an
   exemption is visible and arguable — an unexplained exemption is how a real secret
   quietly becomes permitted. These are documentation and the scanner itself. */
const EXEMPT = {
  "tools/checks/secret-scan.mjs": "This file. It defines the patterns.",
  "tools/hooks/guard-secrets.mjs": "The hook. It imports the patterns and names them in its messages.",
  "tools/checks/guard-fixtures.mjs": "Fixtures deliberately contain example-shaped strings to prove the guards still catch them.",
};

const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "env", "__pycache__", ".netlify", "workbook_extract"]);
const SCAN_EXT = /\.(mjs|js|jsx|ts|tsx|json|sql|py|sh|yml|yaml|toml|md|env|txt|cfg|ini)$/i;
const MAX_BYTES = 2_000_000;

function walk(dir, out = []) {
  let entries;
  try { entries = readdirSync(dir); } catch { return out; }
  for (const e of entries) {
    if (SKIP_DIRS.has(e)) continue;
    const p = join(dir, e);
    let s;
    try { s = statSync(p); } catch { continue; }
    if (s.isDirectory()) walk(p, out);
    else if (SCAN_EXT.test(e) && s.size <= MAX_BYTES) out.push(p);
  }
  return out;
}

/* The stub folder is outside the repo and is where the 8 Aug credentials actually
   lived. Scanned when present — its absence is not a failure, because CI has no
   Desktop. Silence about a location you did not scan is how coverage is overstated
   (rule A3), so it says which of the two it did. */
const EXTRA_ROOTS = [
  { path: "C:/Users/demar/OneDrive/Desktop/Twisted Growers/.claude",
    why: "the Desktop stub config — OneDrive-synced, never committed, and where 23 live credentials sat on 8 Aug 2026" },
];

export function scan(roots) {
  const findings = [];
  for (const r of roots) {
    for (const file of walk(r.path)) {
      const rel = file.replace(/\\/g, "/").replace(ROOT.replace(/\\/g, "/") + "/", "");
      if (EXEMPT[rel]) continue;
      let text;
      try { text = readFileSync(file, "utf8"); } catch { continue; }
      text.split("\n").forEach((line, i) => {
        for (const p of SECRET_PATTERNS) {
          if (p.re.test(line)) findings.push({ file: rel, line: i + 1, name: p.name, fix: p.fix });
        }
      });
    }
  }
  return findings;
}

/* Run as a check only when invoked directly, so the hook can import the patterns. */
if (resolve(process.argv[1] ?? "") === resolve(fileURLToPath(import.meta.url))) {
  const roots = [{ path: ROOT, why: "the repository" }];
  for (const e of EXTRA_ROOTS) {
    if (existsSync(e.path)) roots.push(e);
    else console.log(`secret-scan: not present — ${e.why.split("—")[0].trim()} (skipped, this is expected in CI)`);
  }
  for (const r of roots) console.log(`secret-scan: scanning ${r.why}`);
  for (const [f, why] of Object.entries(EXEMPT)) console.log(`secret-scan: exempt  — ${f}: ${why}`);

  const findings = scan(roots);
  if (findings.length) {
    console.error(`\nsecret-scan: FAIL — ${findings.length} credential(s) found on disk:\n`);
    for (const f of findings) {
      console.error(`  ✗ ${f.file}:${f.line}  — ${f.name}`);
      console.error(`      ${f.fix}`);
    }
    console.error("\nThe value itself is deliberately not printed. Open the line to see it.");
    console.error("A credential in a file is exposed the moment that file is synced, shared or");
    console.error("committed — and it is exposed retroactively, so removing it later is not enough.\n");
    process.exit(1);
  }
  console.log(`\nsecret-scan: PASS — ${SECRET_PATTERNS.length} credential shapes checked, none found.`);
}
