-- BP-16 The Bible, §16.1: every blueprint item is a deployment_check row in section 19, with its lane, hours and
-- acceptance test verbatim from brain/BLUEPRINT_2026_BEAT_THEM_ALL.md. Status changes here only, by measurement.
-- Owner, 14 Sep 2026: go-live in the customer's facility Wed 23 Sep; delivery Fri 18 Sep; 7 am–midnight; three agents.
insert into public.deployment_check (check_key, section, title, why, kind, severity, expected, status, value, detail, active, sort_order)
values
 -- day 1 · Mon 14 Sep
 ('bp.d1.package_360',        '19 Go-live 23 Sep · Blueprint 2026', 'BP-4-1 Package (Tag) 360 page — every list opens into the record', 'Lane Claude · 8 h · Mon 14. f_package_360 live 14 Sep; page assembles it; tag cells in every table link to it; Spotlight finds a tag.', 'manual', 'NO-GO', 'scan/search/click a tag → 360 in < 1.5 s with timeline, lab, documents, money, gaps, findings, tasks, actions', 'PENDING', 'f_package_360 + f_package_search applied 14 Sep 01:55 UTC', null, true, 1901),
 ('bp.d1.findings_exemplar',  '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-2 Findings queue exemplar → rolled to the 60 issue_queue pages', 'Lane Claude · 12 h · Mon 14. Queue by owner/age/severity, decide in place, cash impact, detection anatomy.', 'manual', 'NO-GO', '60 issue_queue pages render the new layout by data; a decision taken in place writes a decision row', 'PENDING', null, null, true, 1902),
 ('bp.d1.deploy_watch',       '19 Go-live 23 Sep · Blueprint 2026', 'BP-16-3 Deploy watch — every deployment watched; a failure is a finding, a push and a bridge job within 2 min', 'Lane Claude · 6 h · Mon 14 night. deploy_watch cron → Netlify API (both sites) + GitHub Actions; deploy_state table; on error: finding NO-GO + push + ai_bridge_jobs fix job; blocks section 19 PASS until green.', 'manual', 'NO-GO', 'kill a build on a branch → finding + push + bridge job within 2 min', 'PENDING', null, null, true, 1903),
 ('bp.d1.sync_watch',         '19 Go-live 23 Sep · Blueprint 2026', 'BP-16-4 Sync watch — every sync green; first failure re-run once, then finding + push + bridge job', 'Lane Claude · 5 h · Mon 14 night. f_sync_status swept every 5 min; off syncs need a note.', 'manual', 'NO-GO', 'break a secret on a test sync → finding + re-run + bridge job within 5 min; restore → green within one sweep', 'PENDING', null, null, true, 1904),
 ('bp.d1.blueprint_gate',     '19 Go-live 23 Sep · Blueprint 2026', 'BP-16-2 blueprint-in-sync gate — every BP id has a row, every row has an id; frozen surfaces refuse a PR; PR titles carry a BP id', 'Lane Claude · 4 h · Mon 14 night. tools/checks/blueprint-in-sync.mjs in CI and the Netlify build.', 'manual', 'WATCH', 'gate FAILs on a PR without a BP id or touching a frozen file', 'PENDING', null, null, true, 1905),
 ('bp.d1.report_issue',       '19 Go-live 23 Sep · Blueprint 2026', 'BP-17-1 Report an issue on every page (humans and bots) → agent_findings scope qa:<view_key> with page, role, figures, screenshot', 'Lane Claude · 6 h · Mon 14. Sits in the existing action bar; no design change.', 'manual', 'WATCH', 'an issue filed from any page appears in Today and Findings within 60 s', 'PENDING', null, null, true, 1906),
 ('bp.d1.bots_certified_only','19 Go-live 23 Sep · Blueprint 2026', 'BP-5-6 Bots answer only from certified figures', 'Lane Grok · 10 h · Mon 14.', 'manual', 'NO-GO', 'Budz/Brain/Top G cite a certified metric or say the figure is uncertified', 'PENDING', null, null, true, 1907),
 ('bp.d1.bot_page_walk',      '19 Go-live 23 Sep · Blueprint 2026', 'BP-17-2 Bot page-walk — every enabled page opened nightly and after each deploy; defects filed with screenshots', 'Lane Grok (walk) + Claude (intake, dedupe) · 12 + 4 h · Mon 14.', 'manual', 'WATCH', 'after a deploy every page has a fresh walk result within 2 h', 'PENDING', null, null, true, 1908),
 ('bp.d1.metrc_certificates', '19 Go-live 23 Sep · Blueprint 2026', 'BP-16-5 Population certificates — plants, packages, harvests, transfers, COAs, employees, two derivations each', 'Lane GPT · 12 h · Mon 14. Signed on the certification board by Fri 18; re-measured hourly.', 'manual', 'NO-GO', 'every population has a certificate row with two derivations that agree within tolerance', 'PENDING', null, null, true, 1909),
 -- day 2 · Tue 15
 ('bp.d2.setup_form',         '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-3 Setup form exemplar (Valuation rates) → rolled to the 251 data_browser pages', 'Lane Claude · 15 h · Tue 15. List + edit-in-place, validation, history, impact-before-save.', 'manual', 'NO-GO', '251 pages render the Setup form by data; an edit writes with history', 'PENDING', null, null, true, 1911),
 ('bp.d2.hr_live',            '19 Go-live 23 Sep · Blueprint 2026', 'BP-12g HR platform live at /hr from the OS menu (PR #238 merged, owner switches flipped)', 'Lane Claude + owner · 4 h · Tue 15.', 'manual', 'NO-GO', 'first real sign-in from the OS lands on the HR dashboard as the right person and role', 'PENDING', null, null, true, 1912),
 ('bp.d2.today_v1',           '19 Go-live 23 Sep · Blueprint 2026', 'BP-8 Today — the decision feed v1 (child of Command Center)', 'Lane Claude · 8 h · Tue 15. decision object; ranked; number captured; one tap.', 'manual', 'NO-GO', 'a finding becomes a decision; taking it executes the effect and shows in the object timeline within 60 s', 'PENDING', null, null, true, 1913),
 ('bp.d2.dash_vs_drills',     '19 Go-live 23 Sep · Blueprint 2026', 'BP-12c Dashboards green against their drills (tile = sum of its items)', 'Lane Grok · 12 h · Tue 15.', 'manual', 'NO-GO', 'tile_drill_contract passes on every department dashboard', 'PENDING', null, null, true, 1914),
 ('bp.d2.sync_liveness',      '19 Go-live 23 Sep · Blueprint 2026', 'BP-16-4 Sync liveness and cursor health, every endpoint', 'Lane GPT · 10 h · Tue 15.', 'manual', 'NO-GO', 'section 11 all PASS; no cursor older than its cadence', 'PENDING', null, null, true, 1915),
 -- day 3 · Wed 16
 ('bp.d3.sheet_vs_metrc',     '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-9 Sheet vs Metrc exemplar — side by side, one-tap "Metrc overrides", neon note, logged discrepancy, weekly review', 'Lane Claude · 12 h · Wed 16. Closes sheets.metrc_override, sheets.discrepancy_rows, sheets.neon_yellow_highlight, sheets.weekly_review.', 'manual', 'NO-GO', 'a discrepancy resolved with one tap writes the neon note, the log row and the review entry', 'PENDING', null, null, true, 1921),
 ('bp.d3.compliance_agent_v1','19 Go-live 23 Sep · Blueprint 2026', 'BP-5-1 Compliance agent v1 — every Metrc-vs-sheet discrepancy filed into Today with the decision ready, each delta cycle', 'Lane Claude · 10 h · Wed 16.', 'manual', 'NO-GO', 'a discrepancy is a decision on the phone within one delta cycle (5 min)', 'PENDING', null, null, true, 1922),
 ('bp.d3.harvest_schedule',   '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-7 Harvest schedule exemplar → 36 schedule pages (calendar + list, drag with rules)', 'Lane Claude · 10 h · Wed 16.', 'manual', 'WATCH', '36 pages render; a drag that breaks a rule is refused with the rule named', 'PENDING', null, null, true, 1923),
 ('bp.d3.ask_front',          '19 Go-live 23 Sep · Blueprint 2026', 'BP-9 Ask front — Budz/Brain call f_ask_view for governed views', 'Lane Grok · 10 h (Claude service 8 h) · Wed 16.', 'manual', 'WATCH', 'the twelve owner benchmark questions answered with certified figures', 'PENDING', null, null, true, 1924),
 ('bp.d3.stock_position',     '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-4 Stock & location exemplar → 29 stock_position pages', 'Lane GPT · 10 h · Wed 16.', 'manual', 'WATCH', '29 pages render with as-of and drill to tags', 'PENDING', null, null, true, 1925),
 -- day 4 · Thu 17
 ('bp.d4.money_spine_v1',     '19 Go-live 23 Sep · Blueprint 2026', 'BP-6 Money spine v1 — journals from tag_event; live P&L, cost per pound by strain × room × cycle, inventory value', 'Lane Claude · 24 h · Thu 17. Indicative until reconciled.', 'manual', 'NO-GO', 'harvest/package/sale post ≤ 60 s; every figure → journal → tag_event', 'PENDING', null, null, true, 1931),
 ('bp.d4.cost_sheet',         '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-6 Cost per pound exemplar → 29 cost_sheet pages (basis shown, journal drill)', 'Lane Claude · 8 h · Thu 17.', 'manual', 'WATCH', '29 pages render; a figure drills to its journals', 'PENDING', null, null, true, 1932),
 ('bp.d4.hr_pages',           '19 Go-live 23 Sep · Blueprint 2026', 'BP-12g HR module pages in the OS wired to /hr', 'Lane Grok · 12 h · Thu 17.', 'manual', 'WATCH', 'each HR menu item opens the matching HR screen as the signed-in person', 'PENDING', null, null, true, 1933),
 ('bp.d4.qb_reconciliation',  '19 Go-live 23 Sep · Blueprint 2026', 'BP-6 QuickBooks reconciliation of the spine — independent derivation (flips indicative → certified where it agrees)', 'Lane GPT · 10 h · Thu 17. Tolerance: owner row (suggest 0.5 %).', 'manual', 'NO-GO', 'P&L, inventory value, cost per pound agree with QuickBooks within tolerance, line by line', 'PENDING', null, null, true, 1934),
 -- day 5 · Fri 18 — delivery
 ('bp.d5.custody_coa',        '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-5/8 Custody chain (24) + COA register (24) exemplars', 'Lane Claude · 12 h · Fri 18.', 'manual', 'WATCH', '48 pages render; gaps highlighted; missing-COA queue', 'PENDING', null, null, true, 1941),
 ('bp.d5.board_signed',       '19 Go-live 23 Sep · Blueprint 2026', 'BP-16-5 Certification board signed for every figure the customer sees on day one; uncertified shown as uncertified', 'Lane Claude (Verifier/Challenger) · 4 h · Fri 18.', 'manual', 'NO-GO', 'zero unlabelled figures on any page the customer opens', 'PENDING', null, null, true, 1942),
 ('bp.d5.onboarding_pack',    '19 Go-live 23 Sep · Blueprint 2026', 'BP-13 Onboarding pack to the customer: accounts and roles, certified-data report, walk-through, help guides, runbook', 'Lane Claude + owner · 6 h · Fri 18.', 'manual', 'NO-GO', 'pack delivered; every employee has an account and role; recipients rows set', 'PENDING', null, null, true, 1943),
 ('bp.d5.scorecards',         '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-10 Goals & scorecards exemplar → 16 pages', 'Lane Grok · 8 h · Fri 18.', 'manual', 'WATCH', '16 pages render with target, actual, trend, owner', 'PENDING', null, null, true, 1944),
 ('bp.d5.role_qa',            '19 Go-live 23 Sep · Blueprint 2026', 'BP-17-3 Per-role QA — every role sees its menu and nothing else; signed', 'Lane GPT · 10 h · Fri 18.', 'manual', 'NO-GO', 'role matrix signed with zero unexplained differences', 'PENDING', null, null, true, 1945),
 -- weekend and Mon 21
 ('bp.d6.sales_desk_v1',      '19 Go-live 23 Sep · Blueprint 2026', 'BP-5-3 Sales desk v1 — allocate sellable tags → manifest draft with COAs → Apex post under review → invoice', 'Lane Claude · 14 h · Sat 19.', 'manual', 'WATCH', 'an order goes order → allocation → manifest → Apex (review) → invoice with no re-keying', 'PENDING', null, null, true, 1951),
 ('bp.d6.work_layer_v1',      '19 Go-live 23 Sep · Blueprint 2026', 'BP-12d Work layer v1 (ClickUp clone): task 360 on any object, List/Board/My Work, forms, timers', 'Lane Claude · 12 h · Sat 19.', 'manual', 'WATCH', 'a task on a tag knows the tag COA state; a timer costs the batch at the real rate', 'PENDING', null, null, true, 1952),
 ('bp.d7.dispensary_portal',  '19 Go-live 23 Sep · Blueprint 2026', 'BP-11 Dispensary portal v1 — customer role, read-only: COAs, orders, manifests, invoices', 'Lane Claude · 12 h · Sun 20.', 'manual', 'WATCH', 'a customer account sees only its own objects', 'PENDING', null, null, true, 1961),
 ('bp.d7.rules_editor',       '19 Go-live 23 Sep · Blueprint 2026', 'BP-12b-11 Business rules exemplar → 39 rules_editor pages', 'Lane Claude · 8 h · Sun 20.', 'manual', 'WATCH', '39 pages render; edits keep history and show where used', 'PENDING', null, null, true, 1962),
 ('bp.d8.my_views',           '19 Go-live 23 Sep · Blueprint 2026', 'BP-7 My views v1 — saved views on every archetype page; share; pin', 'Lane Claude · 10 h · Mon 21.', 'manual', 'WATCH', 'a saved view is shared and pinned; one definition per measure', 'PENDING', null, null, true, 1971),
 ('bp.d8.agents_v1',          '19 Go-live 23 Sep · Blueprint 2026', 'BP-5-2/5 Harvest & Rooms v1 + People v1 — takedown proposals and schedule drafts into Today', 'Lane Claude · 12 h · Mon 21.', 'manual', 'WATCH', 'a takedown proposal and a schedule draft appear in Today as decisions', 'PENDING', null, null, true, 1972),
 ('bp.d8.cycle_compare',      '19 Go-live 23 Sep · Blueprint 2026', 'BP-10 Cycle compare — actuals by strain × room × cycle (the simulator base)', 'Lane Claude · 6 h · Mon 21.', 'manual', 'WATCH', 'last three cycles compared per room with certified yields', 'PENDING', null, null, true, 1973),
 ('bp.d8.dry_run',            '19 Go-live 23 Sep · Blueprint 2026', 'BP-13 Dry run with the customer''s own users on production', 'Lane GPT · 8 h · Mon 21 (second run Tue 22).', 'manual', 'NO-GO', 'every role completes the 15-minute walk-through without a defect', 'PENDING', null, null, true, 1974),
 -- Tue 22 freeze · Wed 23 go-live
 ('bp.d9.freeze_and_certify', '19 Go-live 23 Sep · Blueprint 2026', 'BP-13 Freeze Tue 22 12:00; certification pass; audit pack; runbook; fixes only', 'Lane all · Tue 22.', 'manual', 'NO-GO', 'every NO-GO row in section 19 PASS or explicitly deferred by the owner', 'PENDING', null, null, true, 1981),
 ('bp.d10.go_live',           '19 Go-live 23 Sep · Blueprint 2026', 'BP-13 Go-live Wed 23 Sep in the customer''s facility — Watchdog on, one agent on call, rollback ready', 'Lane all · Wed 23.', 'manual', 'NO-GO', 'day one closes with zero silent failures and every issue filed and owned', 'PENDING', null, null, true, 1982),
 ('deploy.production_green',  '19 Go-live 23 Sep · Blueprint 2026', 'BP-16-3 Production build of main is green (blocks every other section-19 PASS while red)', 'Auto once deploy_watch lands; until then read from Netlify.', 'manual', 'NO-GO', 'latest main deploy state = ready', 'PASS', 'main@2fc9815 ready 01:24 UTC 14 Sep', null, true, 1900),
 -- owner rows
 ('owner.bp_roles_list',      '19 Go-live 23 Sep · Blueprint 2026', 'Owner: role for every employee at the customer (32 in employees)', 'Unblocks accounts and per-role QA.', 'owner', 'OWNER', 'list received', 'PENDING', null, null, true, 1991),
 ('owner.bp_alert_recipients','19 Go-live 23 Sep · Blueprint 2026', 'Owner: day-one alert recipients and channels (rows, never code)', 'Unblocks deploy watch, sync watch, Today push.', 'owner', 'OWNER', 'recipient rows exist', 'PENDING', null, null, true, 1992),
 ('owner.bp_tolerance',       '19 Go-live 23 Sep · Blueprint 2026', 'Owner: reconciliation tolerance for the money spine (suggest 0.5 %)', 'Unblocks certified vs indicative on money figures.', 'owner', 'OWNER', 'rule row set', 'PENDING', null, null, true, 1993),
 ('owner.bp_ask_questions',   '19 Go-live 23 Sep · Blueprint 2026', 'Owner: the twelve benchmark questions Ask must answer with certified figures', 'Unblocks BP-9 acceptance.', 'owner', 'OWNER', 'twelve questions listed', 'PENDING', null, null, true, 1994),
 ('owner.bp_page_marks',      '19 Go-live 23 Sep · Blueprint 2026', 'Owner: page-decision marks (upgrade now / later / leave / retire) — unmarked pages are not touched', 'docs/PAGE_DECISION_REGISTER.md generated Mon 14.', 'owner', 'OWNER', 'marks recorded in nav_registry.upgrade_decision', 'PENDING', null, null, true, 1995)
on conflict (check_key) do update set section = excluded.section, title = excluded.title, why = excluded.why, kind = excluded.kind, severity = excluded.severity,
  expected = excluded.expected, sort_order = excluded.sort_order, active = true;;
