/* THE HARVEST CYCLE IS AN EDITABLE NUMBER. IT IS NOW EDITABLE EVERYWHERE.
 *
 * OWNER, 17 Aug 2026, and this is a standing instruction, not a one-off:
 *   "DO NOT ASK ME AGAIN ABOUT HARVEST CYCLE; THIS NUMBER IS NOT HARDWIRED, UPPER
 *    MANAGEMENT CAN CHANGE THIS NUMBER AS NEEDED AND MUST BE MAPPED AND WIRED FULLY
 *    TO BE AN EDITABLE NUMBER OF PULLS."
 *
 * The config rows already existed and were already correct:
 *
 *     room_cycle_days         56    how long a room takes to come back round
 *     pull_interval_days      14    one takedown every other week
 *     room_turnover_max_days   2    take down, re-room and clean inside this
 *     room_capacity_f1..f4          1140 / 1050 / 1140 / 1050
 *     tables_per_room          4
 *     pull_target_dried_lb   180
 *
 * What was wrong is that four surfaces did not read them. They carried the number as a
 * literal, so changing the row changed nothing on screen - and worse, two of them
 * PRINTED "56" in their own sentences, meaning the platform would confidently tell a
 * manager the wrong cycle length the moment he changed it.
 *
 *   v_harvest_enforcement   room_cycle_days <> 56, and 13/15 for the facility gap
 *   v_room_turn_audit       read f_rule correctly, then said "the 56 day cycle" in prose
 *   v_admin_alerts          "every room turns on 56 days" in prose
 *   v_schedule_compliance   "on all 26 rows" in prose
 *
 * All four now derive from the rows. The number of pulls is not stored anywhere and
 * must not be: it FOLLOWS from the interval. 365 / pull_interval_days. Change the
 * interval to 10 and the year holds 36 pulls, with no second number to keep in step.
 * A stored pull count would be a duplicate definition of a derived fact, which is the
 * defect this platform keeps finding.
 *
 * f_pulls_per_year() exists so nobody writes 26 into anything ever again.
 *
 * WHAT IS DELIBERATELY NOT DONE HERE. The 26 rows in harvest_pulls are the 2026 plan as
 * issued and are NOT regenerated by this migration. Silently rewriting a published
 * schedule under a manager's feet - moving dates people have staffed against - is a far
 * worse failure than a stale one. Regeneration belongs to tg_propose_schedule, which
 * already exists and drafts for approval before posting. This makes every READER honest;
 * proposing a new plan stays a deliberate act.
 */

create or replace function public.f_pulls_per_year()
returns numeric
language sql
stable
set search_path to 'public'
as $$
  /* Derived, never stored. One takedown every pull_interval_days. */
  select round(365.0 / nullif(public.f_rule('pull_interval_days'), 0), 0)
$$;

comment on function public.f_pulls_per_year() is
  'How many pulls a year the current cadence produces. DERIVED from conversion_factors.pull_interval_days and never stored - a stored count would be a second definition of the same fact and would drift the moment upper management changed the interval. At 14 days this is 26. Owner instruction 17 Aug 2026: the cycle is an editable number and every reader must follow it.';

create or replace view public.v_harvest_enforcement as
 SELECT pull_no,
    harvest_date,
    flower_room,
    room_cycle_no,
    room_cycle_days,
    facility_days_since_last_pull AS facility_gap_days,
        CASE
            WHEN harvest_date < CURRENT_DATE THEN 'past'::text
            WHEN harvest_date <= (CURRENT_DATE + public.f_rule('pull_interval_days')::int) THEN 'upcoming'::text
            ELSE 'scheduled'::text
        END AS horizon,
    /* Was `<> 56`. Now the configured cycle, so a change to room_cycle_days is obeyed
       here instead of silently ignored. */
    room_cycle_days IS NOT NULL AND room_cycle_days <> public.f_rule('room_cycle_days') AS cycle_violation,
    /* Was a hardcoded 13..15 window. That is the interval plus or minus the weekend
       stagger, both of which are rows. */
    facility_days_since_last_pull IS NOT NULL
      AND (facility_days_since_last_pull < (public.f_rule('pull_interval_days') - coalesce(public.f_rule('weekend_pull_shift_days'), 2))
        OR facility_days_since_last_pull > (public.f_rule('pull_interval_days') + coalesce(public.f_rule('weekend_pull_shift_days'), 2)))
      AS cadence_violation,
    (EXISTS ( SELECT 1
           FROM harvest_weights w
          WHERE w.harvest_date = p.harvest_date AND w.flower_room = p.flower_room)) AS weights_reported,
    harvest_date < CURRENT_DATE AND NOT (EXISTS ( SELECT 1
           FROM harvest_weights w
          WHERE w.harvest_date = p.harvest_date AND w.flower_room = p.flower_room)) AS overdue_reporting,
    (EXISTS ( SELECT 1
           FROM harvest_pulls p2
          WHERE p2.harvest_date = p.harvest_date AND p2.id <> p.id)) AS same_day_overlap,
    day2_replant_date,
    dry_start,
    dry_day_14,
    cultivars
   FROM harvest_pulls p
  ORDER BY harvest_date;

comment on view public.v_harvest_enforcement is
  'Plan-versus-rule enforcement on the harvest schedule. Every threshold is read from conversion_factors - room_cycle_days, pull_interval_days, weekend_pull_shift_days - and none is written into this view. Before 17 Aug 2026 it compared against a literal 56 and a literal 13..15 window, so upper management could change the cycle and this view would go on enforcing the old one without saying so.';;
