-- GROK-WHY: Already applied in production as 20260912194206 hr_04_tables_d.
-- Another desk ran this. Filed here so migration-drift can pass and the Bots paid key can ship on Sync.
-- Exact SQL from supabase_migrations.schema_migrations.statements. No ledger rewrite. Metrc read-only.

-- TG HR platform, part 04: tables 191–251 of 251 (schema only, from vip-hr-platform's catalog).
set local search_path to hr, public, extensions;
create table hr.product_catalog (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  name text not null,
  sku text,
  category text default 'General'::text not null,
  description text,
  price_retail numeric,
  price_cost numeric,
  brand text,
  image_url text,
  quiz_questions jsonb default '[]'::jsonb,
  is_active boolean default true not null,
  sort_order integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  msrp numeric(12,2),
  comp_price numeric(12,2),
  status text default 'active'::text not null,
  added_date date default CURRENT_DATE not null,
  upsell_skus text[] default '{}'::text[] not null,
  constraint product_catalog_pkey PRIMARY KEY (id)
);
create table hr.product_location_stock (
  id uuid default gen_random_uuid() not null,
  product_id uuid not null,
  node_id uuid not null,
  on_hand integer default 0 not null,
  updated_at timestamp with time zone default now() not null,
  constraint product_location_stock_product_id_node_id_key UNIQUE (product_id, node_id),
  constraint product_location_stock_pkey PRIMARY KEY (id)
);
create table hr.pulse_campaigns (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  title text not null,
  questions jsonb default '[]'::jsonb not null,
  audience jsonb default '{}'::jsonb not null,
  anonymous boolean default true not null,
  status text default 'active'::text not null,
  created_by uuid,
  created_by_name text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint pulse_campaigns_pkey PRIMARY KEY (id)
);
create table hr.pulse_checkins (
  id uuid default gen_random_uuid() not null,
  person_id uuid,
  person_name text,
  node_id uuid,
  mood smallint not null,
  note text,
  flagged boolean default false not null,
  created_at timestamp with time zone default now() not null,
  constraint pulse_checkins_pkey PRIMARY KEY (id),
  constraint pulse_checkins_mood_check CHECK (((mood >= 1) AND (mood <= 5)))
);
create table hr.pulse_responses (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  campaign_id uuid not null,
  person_id uuid,
  responder_name text,
  answers jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint pulse_responses_pkey PRIMARY KEY (id)
);
create table hr.pulse_settings (
  tenant_id uuid not null,
  reminder_mins integer default 30 not null,
  enforce_on_clock_in boolean default false not null,
  enforce_break_return boolean default true not null,
  ai_reminder boolean default true not null,
  updated_at timestamp with time zone default now() not null,
  constraint pulse_settings_pkey PRIMARY KEY (tenant_id)
);
create table hr.recognition (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  from_person uuid not null,
  to_person uuid not null,
  note text not null,
  node_id uuid,
  created_at timestamp with time zone default now(),
  constraint recognition_pkey PRIMARY KEY (id)
);
create table hr.reporting_lines (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  entity_id uuid,
  node_id uuid not null,
  person_id uuid not null,
  manager_id uuid not null,
  relationship text default 'direct'::text not null,
  effective_from date default CURRENT_DATE not null,
  effective_to date,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint reporting_lines_pkey PRIMARY KEY (id),
  constraint no_self_report CHECK ((person_id <> manager_id)),
  constraint reporting_lines_relationship_check CHECK ((relationship = ANY (ARRAY['direct'::text, 'dotted'::text, 'acting'::text])))
);
create table hr.reward_redemptions (
  id uuid default gen_random_uuid() not null,
  person_id uuid,
  reward_id uuid,
  points integer,
  status text default 'redeemed'::text,
  created_at timestamp with time zone default now(),
  constraint reward_redemptions_pkey PRIMARY KEY (id)
);
create table hr.risk_register (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  tenant_id uuid,
  domain text not null,
  title text not null,
  severity text default 'medium'::text not null,
  status text default 'open'::text not null,
  due_date date,
  detail jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint risk_register_pkey PRIMARY KEY (id)
);
create table hr.roles (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  name text not null,
  rank integer default 100 not null,
  lens text default 'operations'::text not null,
  permissions jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint roles_pkey PRIMARY KEY (id)
);
create table hr.sales_contests (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  title text not null,
  description text,
  metric text default 'revenue'::text not null,
  prize text,
  start_date date not null,
  end_date date not null,
  is_active boolean default true not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  contest_type text,
  category text,
  target numeric,
  prize_amount numeric default 0 not null,
  winner_count integer default 1 not null,
  min_hours numeric default 0 not null,
  roles_eligible text,
  budget_code text,
  node_ids uuid[],
  constraint sales_contests_pkey PRIMARY KEY (id)
);
create table hr.sales_goals (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  person_id uuid,
  title text not null,
  description text,
  target_value numeric,
  current_value numeric default 0 not null,
  metric text default 'revenue'::text not null,
  period text default 'monthly'::text not null,
  start_date date,
  end_date date,
  status text default 'active'::text not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint sales_goals_pkey PRIMARY KEY (id)
);
create table hr.sales_logs (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid not null,
  person_id uuid not null,
  sale_date date default CURRENT_DATE not null,
  amount numeric not null,
  units integer,
  category text,
  notes text,
  logged_by uuid,
  created_at timestamp with time zone default now() not null,
  transaction_type text,
  is_upsell boolean default false not null,
  sold_at timestamp with time zone,
  constraint sales_logs_pkey PRIMARY KEY (id)
);
create table hr.sales_promotions (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  title text not null,
  description text,
  discount_type text default 'pct'::text,
  discount_value numeric,
  product_category text,
  start_date date,
  end_date date,
  is_active boolean default true not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint sales_promotions_pkey PRIMARY KEY (id)
);
create table hr.sales_voids (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid,
  person_id uuid,
  sale_id uuid,
  amount numeric(12,2) default 0 not null,
  units integer default 1 not null,
  category text,
  reason text,
  manager_approved boolean default false not null,
  suspicious boolean default false not null,
  original_sale_date date,
  void_at timestamp with time zone default now() not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint sales_voids_pkey PRIMARY KEY (id)
);
create table hr.sched_coverage_ask (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  ask_date date not null,
  slot text not null,
  requester_id uuid,
  message text,
  channel text default 'both'::text not null,
  urgency text default 'normal'::text not null,
  blast boolean default false not null,
  created_at timestamp with time zone default now() not null,
  constraint sched_coverage_ask_pkey PRIMARY KEY (id),
  constraint sched_coverage_ask_channel_check CHECK ((channel = ANY (ARRAY['both'::text, 'app'::text, 'text'::text]))),
  constraint sched_coverage_ask_urgency_check CHECK ((urgency = ANY (ARRAY['normal'::text, 'high'::text, 'critical'::text])))
);
create table hr.sched_coverage_ask_recipient (
  id uuid default gen_random_uuid() not null,
  ask_id uuid not null,
  person_id uuid not null,
  status text default 'pending'::text not null,
  reason text,
  responded_at timestamp with time zone,
  constraint sched_coverage_ask_recipient_ask_id_person_id_key UNIQUE (ask_id, person_id),
  constraint sched_coverage_ask_recipient_pkey PRIMARY KEY (id),
  constraint sched_coverage_ask_recipient_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'declined'::text])))
);
create table hr.sched_coverage_targets (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  slot text not null,
  kh_required integer default 0 not null,
  assoc_required integer default 0 not null,
  updated_at timestamp with time zone default now() not null,
  constraint sched_coverage_targets_node_id_slot_key UNIQUE (node_id, slot),
  constraint sched_coverage_targets_pkey PRIMARY KEY (id),
  constraint sched_coverage_targets_assoc_required_check CHECK ((assoc_required >= 0)),
  constraint sched_coverage_targets_kh_required_check CHECK ((kh_required >= 0))
);
create table hr.sched_on_call (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  on_date date not null,
  person_id uuid not null,
  created_at timestamp with time zone default now() not null,
  constraint sched_on_call_node_id_on_date_person_id_key UNIQUE (node_id, on_date, person_id),
  constraint sched_on_call_pkey PRIMARY KEY (id)
);
create table hr.schedule_snapshots (
  id uuid default gen_random_uuid() not null,
  schedule_id uuid not null,
  node_id uuid not null,
  tenant_id uuid,
  week_start date not null,
  snapshot_type text not null,
  version_no integer not null,
  snapshot_data jsonb not null,
  reason text,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  retain_until date not null,
  constraint schedule_snapshots_pkey PRIMARY KEY (id),
  constraint schedule_snapshots_snapshot_type_check CHECK ((snapshot_type = ANY (ARRAY['original_posted'::text, 'revision'::text])))
);
create table hr.schedules (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  week_start date not null,
  status text default 'draft'::text not null,
  published_by uuid,
  published_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint schedules_node_id_week_start_key UNIQUE (node_id, week_start),
  constraint schedules_pkey PRIMARY KEY (id),
  constraint schedules_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text, 'locked'::text])))
);
create table hr.shift_bookend_checklists (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid not null,
  checklist_date date default CURRENT_DATE not null,
  bookend_type text not null,
  status text default 'in_progress'::text not null,
  completion_pct integer default 0 not null,
  items_done integer default 0 not null,
  items_total integer default 0 not null,
  checked_items jsonb default '{}'::jsonb not null,
  signed_by text,
  notes text,
  author_name text,
  author_id uuid,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint shift_bookend_checklists_node_id_checklist_date_bookend_typ_key UNIQUE (node_id, checklist_date, bookend_type),
  constraint shift_bookend_checklists_pkey PRIMARY KEY (id),
  constraint shift_bookend_checklists_bookend_type_check CHECK ((bookend_type = ANY (ARRAY['OPEN'::text, 'CLOSE'::text]))),
  constraint shift_bookend_checklists_status_check CHECK ((status = ANY (ARRAY['in_progress'::text, 'submitted'::text, 'locked'::text])))
);
create table hr.shift_bookends (
  id uuid default gen_random_uuid() not null,
  shift_id uuid,
  type text default 'briefing'::text not null,
  state text default 'open'::text not null,
  opened_by uuid,
  opened_at timestamp with time zone default now(),
  closed_at timestamp with time zone,
  ai_draft jsonb default '{}'::jsonb,
  manager_notes text,
  labor_delta text,
  acknowledged_by jsonb default '{}'::jsonb,
  constraint shift_bookends_shift_id_key UNIQUE (shift_id),
  constraint shift_bookends_pkey PRIMARY KEY (id)
);
create table hr.shift_breaks (
  id uuid default gen_random_uuid() not null,
  shift_id uuid not null,
  break_type text not null,
  start_time time without time zone,
  end_time time without time zone,
  duration_min integer not null,
  paid boolean default false not null,
  source text default 'manual'::text not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint shift_breaks_pkey PRIMARY KEY (id),
  constraint shift_breaks_break_type_check CHECK ((break_type = ANY (ARRAY['meal'::text, 'rest'::text]))),
  constraint shift_breaks_source_check CHECK ((source = ANY (ARRAY['legal'::text, 'custom'::text, 'manual'::text])))
);
create table hr.shift_checklist_runs (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid not null,
  shift text not null,
  run_date date default CURRENT_DATE not null,
  items jsonb default '{}'::jsonb not null,
  signed_off boolean default false not null,
  signed_by text,
  signed_by_id uuid,
  signed_at timestamp with time zone,
  updated_at timestamp with time zone default now() not null,
  constraint shift_checklist_runs_node_id_shift_run_date_key UNIQUE (node_id, shift, run_date),
  constraint shift_checklist_runs_pkey PRIMARY KEY (id)
);
create table hr.shift_claims (
  id uuid default gen_random_uuid() not null,
  shift_id uuid not null,
  person_id uuid not null,
  node_id uuid not null,
  status text default 'pending'::text not null,
  note text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  constraint shift_claims_shift_id_person_id_key UNIQUE (shift_id, person_id),
  constraint shift_claims_pkey PRIMARY KEY (id),
  constraint shift_claims_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text])))
);
create table hr.shift_exceptions (
  id uuid default gen_random_uuid() not null,
  shift_id uuid not null,
  node_id uuid not null,
  exception_type text not null,
  swap_person_id uuid,
  reported_by uuid,
  notes text,
  created_at timestamp with time zone default now(),
  person_id uuid,
  type text generated always as (exception_type) stored,
  excused boolean,
  callout_reason text,
  disciplinary_record_id uuid,
  constraint shift_exceptions_pkey PRIMARY KEY (id),
  constraint shift_exceptions_exception_type_check CHECK ((exception_type = ANY (ARRAY['callout'::text, 'no_show'::text, 'late'::text, 'swap'::text, 'early_leave'::text, 'cancel'::text])))
);
create table hr.shift_notes (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid not null,
  note_date date default CURRENT_DATE not null,
  shift text not null,
  summary text not null,
  tagged jsonb default '[]'::jsonb not null,
  note_type text default 'general'::text not null,
  is_private boolean default false not null,
  follow_up_required boolean default false not null,
  follow_up_note text,
  photo text,
  manager_name text,
  manager_id uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint shift_notes_pkey PRIMARY KEY (id)
);
create table hr.shift_reports (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid not null,
  report_date date default CURRENT_DATE not null,
  shift_type text,
  status text default 'draft'::text not null,
  manager_on_duty text,
  rating integer,
  data jsonb default '{}'::jsonb not null,
  author_name text,
  author_id uuid,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint shift_reports_pkey PRIMARY KEY (id)
);
create table hr.shift_swap_requests (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  requestor_id uuid not null,
  requestor_shift_id uuid not null,
  target_person_id uuid,
  target_shift_id uuid,
  requestor_note text,
  target_note text,
  status text default 'pending'::text not null,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_note text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint shift_swap_requests_pkey PRIMARY KEY (id),
  constraint shift_swap_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'target_accepted'::text, 'target_declined'::text, 'approved'::text, 'denied'::text, 'cancelled'::text])))
);
create table hr.shift_templates (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  tenant_id uuid not null,
  slot text not null,
  label text not null,
  default_start time without time zone not null,
  default_end time without time zone,
  ends_at_close boolean default false not null,
  default_staff_required integer default 1 not null,
  default_keyholders_required integer default 0 not null,
  default_associates_required integer default 0 not null,
  sort_order integer default 0 not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default now(),
  constraint shift_templates_node_id_slot_key UNIQUE (node_id, slot),
  constraint shift_templates_pkey PRIMARY KEY (id),
  constraint shift_templates_slot_check CHECK ((slot = ANY (ARRAY['open'::text, 'mid'::text, 'close'::text])))
);
create table hr.shift_zone_coverage (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  coverage_date date not null,
  slot text,
  person_id uuid not null,
  employee_name text,
  zone_keys text[] not null,
  is_short_staff_coverage boolean default false not null,
  assigned_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint shift_zone_coverage_pkey PRIMARY KEY (id)
);
create table hr.shifts (
  id uuid default gen_random_uuid() not null,
  schedule_id uuid,
  node_id uuid not null,
  person_id uuid,
  role_id uuid,
  zone text,
  shift_date date not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  is_locked boolean default false,
  notes text,
  created_by uuid,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  status text default 'scheduled'::text not null,
  shift_type text default 'custom'::text,
  requires_key boolean default false,
  is_open_shift boolean default false,
  break_start time without time zone,
  break_end time without time zone,
  close_variant text,
  crosses_midnight boolean generated always as ((end_time < start_time)) stored,
  posted_by uuid,
  constraint shifts_pkey PRIMARY KEY (id),
  constraint shift_times_valid CHECK ((end_time <> start_time))
);
create table hr.sign_requests (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  node_name text,
  template_id text not null,
  template_name text not null,
  fields jsonb default '[]'::jsonb not null,
  signer_id uuid,
  signer_name text,
  status text default 'draft'::text not null,
  signature text,
  signature_kind text,
  signed_at timestamp with time zone,
  sent_at timestamp with time zone,
  audit jsonb default '[]'::jsonb not null,
  created_by uuid,
  created_by_name text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint sign_requests_pkey PRIMARY KEY (id)
);
create table hr.spiff_payouts (
  id uuid default gen_random_uuid() not null,
  program_id uuid not null,
  person_id uuid not null,
  node_id uuid not null,
  amount numeric not null,
  notes text,
  awarded_by uuid,
  awarded_at timestamp with time zone default now() not null,
  tenant_id uuid,
  quantity integer default 1,
  transaction_id text,
  status text default 'pending'::text,
  verified_by uuid,
  verified_at timestamp with time zone,
  constraint spiff_payouts_pkey PRIMARY KEY (id)
);
create table hr.spiff_programs (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  title text not null,
  description text,
  amount numeric not null,
  unit text default 'per_sale'::text not null,
  product_category text,
  start_date date,
  end_date date,
  is_active boolean default true not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  category text,
  rate_type text,
  budget_total numeric,
  cap_daily integer,
  cap_weekly integer,
  eligible_products text,
  eligible_locations text,
  eligible_roles text,
  updated_at timestamp with time zone,
  constraint spiff_programs_pkey PRIMARY KEY (id)
);
create table hr.store_visit_action_items (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  visit_id uuid,
  location_name text,
  item text not null,
  assigned_to text,
  assigned_to_id uuid,
  visit_date date,
  due_date date,
  priority text default 'MEDIUM'::text not null,
  status text default 'OPEN'::text not null,
  completed_at timestamp with time zone,
  completed_by_id uuid,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint store_visit_action_items_pkey PRIMARY KEY (id)
);
create table hr.store_visits (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  location_name text,
  visit_type text default 'Routine'::text not null,
  visit_date date default CURRENT_DATE not null,
  manager_present text,
  visited_by text,
  visited_by_id uuid,
  score integer default 0 not null,
  summary text,
  findings text,
  score_breakdown jsonb default '{}'::jsonb not null,
  checklist jsonb default '{}'::jsonb not null,
  tags text[] default '{}'::text[] not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint store_visits_pkey PRIMARY KEY (id)
);
create table hr.streaks (
  person_id uuid not null,
  current_streak integer default 0,
  longest_streak integer default 0,
  last_break_date date,
  updated_at timestamp with time zone default now(),
  constraint streaks_pkey PRIMARY KEY (person_id)
);
create table hr.supply_requests (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  item_name text not null,
  quantity_needed integer default 1 not null,
  unit text,
  urgency text default 'normal'::text not null,
  status text default 'pending'::text not null,
  requested_by uuid,
  notes text,
  requested_at timestamp with time zone default now(),
  fulfilled_at timestamp with time zone,
  constraint supply_requests_pkey PRIMARY KEY (id),
  constraint supply_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'ordered'::text, 'received'::text, 'cancelled'::text]))),
  constraint supply_requests_urgency_check CHECK ((urgency = ANY (ARRAY['low'::text, 'normal'::text, 'urgent'::text, 'critical'::text])))
);
create table hr.system_incidents (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid,
  system text default ''::text not null,
  severity text default 'medium'::text not null,
  description text default ''::text not null,
  resolved boolean default false not null,
  reported_by uuid,
  reporter_name text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  constraint system_incidents_pkey PRIMARY KEY (id)
);
create table hr.task_projects (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid,
  name text not null,
  description text,
  owner_name text,
  priority text default 'normal'::text not null,
  status text default 'active'::text not null,
  due_date date,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint task_projects_pkey PRIMARY KEY (id)
);
create table hr.tenant_config (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  business_type_key text,
  roles jsonb default '[]'::jsonb,
  zones jsonb default '[]'::jsonb,
  shift_slots jsonb default '[]'::jsonb,
  competencies jsonb default '[]'::jsonb,
  vocabulary jsonb default '{}'::jsonb,
  settings jsonb default '{}'::jsonb,
  updated_at timestamp with time zone default now(),
  constraint tenant_config_tenant_id_node_id_key UNIQUE (tenant_id, node_id),
  constraint tenant_config_pkey PRIMARY KEY (id)
);
create table hr.test_results (
  id uuid default gen_random_uuid() not null,
  batch_id uuid not null,
  analyte text not null,
  value numeric,
  unit text,
  pass boolean,
  is_retest boolean default false,
  source_doc text,
  lab_name text,
  tested_at date,
  entered_by uuid,
  created_at timestamp with time zone default now(),
  constraint test_results_pkey PRIMARY KEY (id)
);
create table hr.tg_batches (
  id text not null,
  node_id text,
  tenant_id uuid,
  strain text,
  source text,
  room text,
  phase text,
  plant_count integer,
  phase_day integer,
  flip_date date,
  projected_chop date,
  cap_flag boolean default false not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint tg_batches_pkey PRIMARY KEY (id)
);
create table hr.time_off_requests (
  id uuid default gen_random_uuid() not null,
  person_id uuid not null,
  node_id uuid not null,
  type text not null,
  start_date date not null,
  end_date date not null,
  total_days integer generated always as (((end_date - start_date) + 1)) stored,
  notes text,
  status text default 'pending'::text not null,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_note text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint time_off_requests_pkey PRIMARY KEY (id),
  constraint time_off_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text, 'cancelled'::text]))),
  constraint time_off_requests_type_check CHECK ((type = ANY (ARRAY['vacation'::text, 'sick'::text, 'personal'::text, 'unpaid'::text, 'bereavement'::text, 'jury_duty'::text, 'other'::text])))
);
create table hr.time_punches (
  id uuid default gen_random_uuid() not null,
  person_id uuid not null,
  node_id uuid not null,
  work_date date default CURRENT_DATE not null,
  punched_in_at timestamp with time zone,
  punched_out_at timestamp with time zone,
  hours_worked numeric generated always as ( CASE WHEN (punched_out_at IS NOT NULL) THEN (EXTRACT(epoch FROM (punched_out_at - punched_in_at)) / (3600)::numeric) ELSE NULL::numeric END) stored,
  notes text,
  edited_by uuid,
  edited_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  constraint time_punches_pkey PRIMARY KEY (id)
);
create table hr.tracked_documents (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  entity_id uuid,
  node_id uuid,
  type hr.doc_type not null,
  title text not null,
  body text,
  content_ref text,
  meta jsonb default '{}'::jsonb not null,
  version integer default 1 not null,
  status hr.doc_status default 'draft'::hr.doc_status not null,
  delivery_type hr.doc_delivery default 'fyi'::hr.doc_delivery not null,
  priority hr.doc_priority default 'normal'::hr.doc_priority not null,
  author uuid,
  published_at timestamp with time zone,
  expires_at timestamp with time zone,
  archived_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint tracked_documents_pkey PRIMARY KEY (id)
);
create table hr.training_assignments (
  id uuid default gen_random_uuid() not null,
  node_id uuid not null,
  trainee_id uuid not null,
  trainer_id uuid,
  competency_key text not null,
  shift_id uuid,
  train_date date not null,
  slot text,
  status text default 'scheduled'::text not null,
  notes text,
  created_by uuid,
  created_at timestamp with time zone default now(),
  constraint training_assignments_pkey PRIMARY KEY (id),
  constraint training_assignments_status_check CHECK ((status = ANY (ARRAY['scheduled'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])))
);
create table hr.training_drills (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid,
  drill_name text not null,
  drill_date date,
  mandatory boolean default false not null,
  status text default 'scheduled'::text not null,
  notes text,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint training_drills_pkey PRIMARY KEY (id)
);
create table hr.training_modules (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  name text not null,
  category text not null,
  description text,
  duration_minutes integer default 30 not null,
  is_required boolean default false not null,
  expires_in_days integer,
  sort_order integer default 0 not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  passing_score integer default 80 not null,
  version text default '1.0'::text not null,
  objectives text default ''::text not null,
  constraint training_modules_pkey PRIMARY KEY (id)
);
create table hr.training_records (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid not null,
  person_id uuid not null,
  module text not null,
  category text default 'general'::text not null,
  completed_at timestamp with time zone,
  score integer,
  expires_at date,
  cert_url text,
  status text default 'assigned'::text not null,
  assigned_by uuid,
  created_at timestamp with time zone default now(),
  module_id uuid,
  progress_pct integer default 0 not null,
  attempts integer default 0 not null,
  started_at timestamp with time zone,
  constraint training_records_pkey PRIMARY KEY (id),
  constraint training_records_category_check CHECK ((category = ANY (ARRAY['general'::text, 'compliance'::text, 'safety'::text, 'product'::text, 'skills'::text, 'onboarding'::text]))),
  constraint training_records_score_check CHECK (((score >= 0) AND (score <= 100))),
  constraint training_records_status_check CHECK ((status = ANY (ARRAY['assigned'::text, 'in_progress'::text, 'completed'::text, 'expired'::text, 'waived'::text])))
);
create table hr.user_settings (
  person_id uuid not null,
  notification_prefs jsonb default '{}'::jsonb not null,
  privacy_prefs jsonb default '{}'::jsonb not null,
  profile_extra jsonb default '{}'::jsonb not null,
  updated_at timestamp with time zone default now() not null,
  constraint user_settings_pkey PRIMARY KEY (person_id)
);
create table hr.user_tasks (
  id uuid default gen_random_uuid() not null,
  node_id uuid,
  assigned_by uuid,
  assigned_to uuid,
  title text not null,
  description text,
  due_date date,
  priority text default 'Medium'::text not null,
  category text default 'Work'::text not null,
  status text default 'not_started'::text not null,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  completed_by uuid,
  updated_at timestamp with time zone,
  updated_by uuid,
  project_id uuid,
  constraint user_tasks_pkey PRIMARY KEY (id)
);
create table hr.vip_positions (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  entity_id uuid,
  node_id uuid not null,
  title text not null,
  headcount_target integer default 1 not null,
  required_skills jsonb default '[]'::jsonb not null,
  required_certs jsonb default '[]'::jsonb not null,
  pay_band jsonb,
  status text default 'active'::text not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint vip_positions_pkey PRIMARY KEY (id),
  constraint vip_positions_status_check CHECK ((status = ANY (ARRAY['active'::text, 'frozen'::text, 'closed'::text])))
);
create table hr.w4_withholding (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  person_id uuid not null,
  filing_status text default 'Single'::text not null,
  allowances integer default 0 not null,
  extra_withholding numeric default 0 not null,
  effective_date date default CURRENT_DATE not null,
  updated_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint w4_withholding_pkey PRIMARY KEY (id)
);
create table hr.wage_history (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  node_id uuid,
  person_id uuid not null,
  effective_date date default CURRENT_DATE not null,
  new_wage numeric not null,
  prior_wage numeric,
  note text,
  changed_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint wage_history_pkey PRIMARY KEY (id)
);
create table hr.weekly_drill_history (
  id uuid default gen_random_uuid() not null,
  person_id uuid,
  node_id uuid,
  drill_type text,
  score integer,
  passed boolean,
  performed_at timestamp with time zone default now(),
  notes text,
  constraint weekly_drill_history_pkey PRIMARY KEY (id)
);
create table hr.workers_comp_claims (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid,
  node_id uuid not null,
  claim_number text,
  person_id uuid,
  employee_name text,
  reported_by uuid,
  reporter_name text,
  incident_date date default CURRENT_DATE not null,
  occurred_at timestamp with time zone,
  type text,
  body_part text,
  description text,
  medical_attention text,
  witnesses text,
  osha_recordable boolean default false not null,
  reported_to_insurance boolean default false not null,
  status text default 'OPEN'::text not null,
  notes jsonb default '[]'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint workers_comp_claims_pkey PRIMARY KEY (id)
);
create table hr.zone_assignments (
  id uuid default gen_random_uuid() not null,
  node_id uuid,
  assignment_date date default CURRENT_DATE not null,
  zone text not null,
  person_id uuid,
  employee_name text,
  start_time time without time zone,
  end_time time without time zone,
  assigned_by uuid,
  created_at timestamp with time zone default now(),
  constraint zone_assignments_pkey PRIMARY KEY (id)
);
