-- METRC EXPORT DROP, 26 AUGUST 2026 - STAGED, NOT TYPED.
--
-- NOT APPLIED. Branch only, held for APPLY.
--
-- Generated by tools/ingest/build_metrc_aug26.py directly from the files in
-- Downloads. Nothing here was retyped by hand: 14,168 transferred package lines and
-- 53,012 inactive plants do not survive transcription, and this session already put
-- one stray character into a deployed edge function that way.
--
-- EACH FILE LANDS IN ITS OWN STAGING TABLE WHOSE COLUMNS ARE THE FILE'S OWN HEADER,
-- ALL TEXT. That is deliberate. Typing a column guesses at a meaning nobody has
-- reviewed, and a wrong guess repeated 14,168 times is far more expensive than a
-- later, reviewed mapping step. Every row carries source_file, file_sha256, licence
-- and the report window, so any figure can be traced back to the bytes it came from.
--
-- WHAT IS NOT HERE, BY INSTRUCTION:
--   * metrc_rpt_point_in_time is untouched, and no 2024-12-31 or 2025-12-31 close is
--     loaded. Agent A owns PIT and the licence-in-key change.
--   * PackagesInventoryReport (4)(5)(6) are SNAPSHOTS, never on-hand. They are staged
--     with their own window and must not be upserted into live quantity or used as
--     Packages Active. On-hand for MP281909 is Packages-Active (507) and nothing else.
--   * Shipped and received quantities are stored as they appear and are never netted.
--   * Adjustment quantities keep Metrc's sign.
--   * The two incoming transfer rows stay unreceived - no received_at is invented.
--   * IL* destinations on transferred packages are lab submits, not sales. Nothing
--     here classifies them; the raw destination licence is preserved for the mapping
--     step to judge.
--
-- COUNT GATE: a file whose parsed rows missed its expected count by more than 1%
-- emitted nothing at all. See the run report in the PR body for what passed.

-- ── stg_mc_tags_voided: 43 rows ──────────────────────────────
create table if not exists public.stg_mc_tags_voided (
  tag text,
  source_file text not null,
  file_sha256 text not null,
  licence text not null,
  file_window text,
  ingested_at timestamptz not null default now()
);
alter table public.stg_mc_tags_voided enable row level security;
drop policy if exists stg_mc_tags_voided_read on public.stg_mc_tags_voided;
create policy stg_mc_tags_voided_read on public.stg_mc_tags_voided for select to authenticated using (true);
insert into public.stg_mc_tags_voided (tag,source_file,file_sha256,licence,file_window) values
('1A40A020000E5B1000026667','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000000988','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000000995','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000000997','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000000998','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000000999','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000001509','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000001510','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000001511','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000001512','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000001513','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000001662','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000001663','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002108','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002109','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002110','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002111','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002266','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002267','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002268','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002269','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002270','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002271','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002272','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002273','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002575','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002576','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002578','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002579','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002584','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002585','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002588','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002589','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002594','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002595','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000002619','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000003087','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000003088','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000004296','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000004297','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000005116','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000005324','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null),
('1A40A030000E5B1000006027','Metrc-Massachusetts-MC281714-Tags-Voided.xlsx','37b2096c7551b1867d1bb196e15df223c76cba18b69fa7b99aeddb9d289586bd','MC281714',null);
