-- Deployment tracker, section 18 — the Twisted Growers HR platform (clone of vip-hr-hub, owner direction 12 Sep 2026).
insert into public.deployment_check (check_key, section, title, why, kind, severity, expected, status, value, detail, last_run_at, active, sort_order)
values
 ('hrp.schema_loaded', '18 HR platform', 'VIP''s HR schema is in TG''s database as schema hr — schema only, zero VIP rows', 'Exported from vip-hr-platform''s catalog through a temporary export function (dropped after) and loaded into TG''s project: 251 tables, 776 functions (4 repaired: documents.version text vs integer), 287 FKs, 638 indexes, RLS on all 251, 76 policies, 8 triggers. No row was read or copied. Lane: Claude (done).', 'manual', 'GO', '251 tables / 776 functions / 0 rows', 'PASS', '251 / 776 / 287 FKs / 0 rows', 'Measured 12 Sep 2026 after hr_00..hr_05.', now(), true, 170),
 ('hrp.rpc_coverage', '18 HR platform', 'Every RPC the 136 screens call exists', 'The screens make 495 distinct RPC calls. 492 existed in VIP''s schema; ceo_company_kpi_strip, nav_registry_get (HQ = the TG OS, schema public) and send_emergency_contact_reminders were built. Re-measure whenever a screen changes. Lane: Claude (done).', 'manual', 'GO', '0 missing', 'PASS', '495 called / 495 exist', 'The CEO strip returns dollar tiles as null (shown as —) until the Apex lane''s certified revenue view exists — never a made-up figure.', now(), true, 171),
 ('hrp.tg_org_and_people', '18 HR platform', 'Twisted Growers org tree, roles and people live in the HR schema, bridged from the OS', 'Company → Lakeville Facility → the 8 departments; 12 roles (the names the screens gate on, plus TG''s; retail roles kept for the dispensary); 32 people (27 active) from public.employees with department assignments, kept in step by trigger on employees and app_users. OS login = same person (session_login). 0 employees have a PIN yet — HR sets them (admin_reset_pin / OS onboarding). Lane: Claude (done); HR (PINs).', 'manual', 'GO', 'people = OS employees; every active person assigned', 'PASS', '32 people / 27 active / 27 assigned / 0 PINs', 'Measured 12 Sep 2026.', now(), true, 172),
 ('hrp.app_built_and_served', '18 HR platform', 'The HR app builds from app/hr, runs on TG''s project, and is served at /hr', 'vip-hr-hub main (17 Jul) cloned into app/hr: TG branding, TG + VIP themes with light/dark/system, greetings rewritten, VIP content replaced (DRAFT skeletons or empty states), OS single sign-on, Netlify site tg-hr linked to the repo (base app/hr) and proxied by the OS at /hr/*. Lane: Claude (done).', 'manual', 'GO', 'builds green; /hr serves the login', 'PASS', 'tg-hr.netlify.app/hr/', 'A local CLI deploy was scrubbing the project URL out of the bundle in transit (asterisks); Netlify now builds from the repo instead.', now(), true, 173),
 ('owner.hr_expose_schema', '18 HR platform', 'Owner: expose schema hr in Supabase (Settings › API › Exposed schemas)', 'PostgREST serves only listed schemas. Until hr is added, every HR call returns "schema must be one of…". One switch in the Supabase dashboard: Project Settings › API › Exposed schemas → add hr. Claude cannot change project settings.', 'owner', 'OWNER', 'hr listed', 'PENDING', null, 'https://supabase.com/dashboard/project/fxetuqjryttnypgepsru/settings/api', null, true, 174),
 ('owner.hr_anonymous_signin', '18 HR platform', 'Owner: enable anonymous sign-ins in Supabase Auth (kiosk / Employee ID + PIN path)', 'Nothing in TG is granted to anon (rule E6). A person at the time clock has no OS session, so the HR app opens an anonymous auth session first (role authenticated, RLS decides) and then verifies the PIN. Supabase refuses that until Authentication › Providers › Anonymous sign-ins is on. OS users are unaffected (they already have a session).', 'owner', 'OWNER', 'anonymous sign-ins on', 'PENDING', null, 'https://supabase.com/dashboard/project/fxetuqjryttnypgepsru/auth/providers', null, true, 175),
 ('hrp.first_login_verified', '18 HR platform', 'First real sign-in from the OS lands on the HR dashboard as the right person and role', 'After the two owner switches: open /hr from the OS as the owner → dashboard, role Admin/Owner, nodes = company tree. Then a floor employee with a PIN at the kiosk. Claude never enters credentials; verified with the owner at the screen. Lane: Claude + owner.', 'manual', 'NO-GO', 'owner in as Admin/Owner; one employee in by PIN', 'PENDING', null, null, null, true, 176),
 ('hrp.defake_six_screens', '18 HR platform', 'Six screens still generate figures from a seed instead of reading records', 'Found in the clone: AiScheduler (seeded roster), ComplianceExpirations (seeded certifications), FlightRisk (seeded call-outs/lates), Forms (seeded submissions), Huddle (seeded sales progress), LaborBudget (seeded actual hours/OT). VIP shipped them that way. Each is rewired to its real table/RPC or shows an honest empty state; AI Schedule calls TG''s drafter (f_draft_schedule / f_schedule_candidates). Lane: Claude.', 'manual', 'NO-GO', '0 seeded generators in src', 'PENDING', '6 screens', null, null, true, 177),
 ('hrp.content_for_hr', '18 HR platform', 'HR writes Twisted Growers'' handbook, policies, procedures, courses and benefits in the platform', 'VIP''s content is gone. The Handbook Builder, Manual, Policies, Academy and Benefits screens carry Twisted Growers / Massachusetts skeletons marked DRAFT (MA minimum wage, Earned Sick Time, PFML, meal breaks, CCC agent registration, 935 CMR 500) for HR to complete and publish; law alerts and the MA compliance checklist say "verify with counsel". Nothing is company policy until published. Lane: HR; owner.', 'manual', 'WATCH', 'handbook published; policies acknowledged', 'PENDING', null, null, null, true, 178),
 ('hrp.os_menu_link', '18 HR platform', 'Human Resources in the OS side menu opens /hr', 'The OS menu entry points at the HR platform (same origin, same sign-in). Lane: Claude (menu entry) — a rename/consolidate/add on the menu is allowed under the frozen-surfaces ruling.', 'manual', 'WATCH', 'menu → /hr', 'PENDING', null, null, null, true, 179),
 ('hrp.pr_merged', '18 HR platform', 'Branch claude/hr-platform merged so main carries app/hr and the /hr proxy', 'Netlify builds tg-hr from claude/hr-platform until merge; the OS proxy in netlify.toml lands with the merge. Lane: owner review.', 'manual', 'WATCH', 'merged', 'PENDING', null, null, null, true, 180)
on conflict (check_key) do update set section = excluded.section, title = excluded.title, why = excluded.why, kind = excluded.kind, severity = excluded.severity,
  expected = excluded.expected, status = excluded.status, value = excluded.value, detail = excluded.detail, last_run_at = excluded.last_run_at, sort_order = excluded.sort_order, active = true;
