-- METRC EXPORT DROP, 26 AUGUST 2026 - STAGED, NOT TYPED.
--
-- NOT APPLIED. Branch only, held for APPLY.
--
-- Generated by tools/ingest/build_metrc_aug26.py directly from the files in
-- Downloads. Nothing here was retyped by hand: 14,168 transferred package lines and
-- 53,012 inactive plants do not survive transcription, and this session already put
-- one stray character into a deployed edge function that way.
--
-- EACH FILE LANDS IN ITS OWN STAGING TABLE WHOSE COLUMNS ARE THE FILE'S OWN HEADER,
-- ALL TEXT. That is deliberate. Typing a column guesses at a meaning nobody has
-- reviewed, and a wrong guess repeated 14,168 times is far more expensive than a
-- later, reviewed mapping step. Every row carries source_file, file_sha256, licence
-- and the report window, so any figure can be traced back to the bytes it came from.
--
-- WHAT IS NOT HERE, BY INSTRUCTION:
--   * metrc_rpt_point_in_time is untouched, and no 2024-12-31 or 2025-12-31 close is
--     loaded. Agent A owns PIT and the licence-in-key change.
--   * PackagesInventoryReport (4)(5)(6) are SNAPSHOTS, never on-hand. They are staged
--     with their own window and must not be upserted into live quantity or used as
--     Packages Active. On-hand for MP281909 is Packages-Active (507) and nothing else.
--   * Shipped and received quantities are stored as they appear and are never netted.
--   * Adjustment quantities keep Metrc's sign.
--   * The two incoming transfer rows stay unreceived - no received_at is invented.
--   * IL* destinations on transferred packages are lab submits, not sales. Nothing
--     here classifies them; the raw destination licence is preserved for the mapping
--     step to judge.
--
-- COUNT GATE: a file whose parsed rows missed its expected count by more than 1%
-- emitted nothing at all. See the run report in the PR body for what passed.

-- ── stg_mp_tags_voided: 11 rows ──────────────────────────────
create table if not exists public.stg_mp_tags_voided (
  tag text,
  source_file text not null,
  file_sha256 text not null,
  licence text not null,
  file_window text,
  ingested_at timestamptz not null default now()
);
alter table public.stg_mp_tags_voided enable row level security;
drop policy if exists stg_mp_tags_voided_read on public.stg_mp_tags_voided;
create policy stg_mp_tags_voided_read on public.stg_mp_tags_voided for select to authenticated using (true);
insert into public.stg_mp_tags_voided (tag,source_file,file_sha256,licence,file_window) values
('1A40A030000E5B2000001281','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000001658','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000001662','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000003283','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000004029','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000004227','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000004233','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000009481','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000009482','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000009483','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null),
('1A40A030000E5B2000009484','Metrc-Massachusetts-MP281909-Tags-Voided.xlsx','ca3cc777c87f4dcde135ce3ab2b7030a570dbff7886e50e070cecc142fe754bd','MP281909',null);
