-- METRC EXPORT DROP, 26 AUGUST 2026 - STAGED, NOT TYPED.
--
-- NOT APPLIED. Branch only, held for APPLY.
--
-- Generated by tools/ingest/build_metrc_aug26.py directly from the files in
-- Downloads. Nothing here was retyped by hand: 14,168 transferred package lines and
-- 53,012 inactive plants do not survive transcription, and this session already put
-- one stray character into a deployed edge function that way.
--
-- EACH FILE LANDS IN ITS OWN STAGING TABLE WHOSE COLUMNS ARE THE FILE'S OWN HEADER,
-- ALL TEXT. That is deliberate. Typing a column guesses at a meaning nobody has
-- reviewed, and a wrong guess repeated 14,168 times is far more expensive than a
-- later, reviewed mapping step. Every row carries source_file, file_sha256, licence
-- and the report window, so any figure can be traced back to the bytes it came from.
--
-- WHAT IS NOT HERE, BY INSTRUCTION:
--   * metrc_rpt_point_in_time is untouched, and no 2024-12-31 or 2025-12-31 close is
--     loaded. Agent A owns PIT and the licence-in-key change.
--   * PackagesInventoryReport (4)(5)(6) are SNAPSHOTS, never on-hand. They are staged
--     with their own window and must not be upserted into live quantity or used as
--     Packages Active. On-hand for MP281909 is Packages-Active (507) and nothing else.
--   * Shipped and received quantities are stored as they appear and are never netted.
--   * Adjustment quantities keep Metrc's sign.
--   * The two incoming transfer rows stay unreceived - no received_at is invented.
--   * IL* destinations on transferred packages are lab submits, not sales. Nothing
--     here classifies them; the raw destination licence is preserved for the mapping
--     step to judge.
--
-- COUNT GATE: a file whose parsed rows missed its expected count by more than 1%
-- emitted nothing at all. See the run report in the PR body for what passed.

-- ── stg_mp_packages_intransit: 141 rows ──────────────────────────────
create table if not exists public.stg_mp_packages_intransit (
  tag text,
  source_file text not null,
  file_sha256 text not null,
  licence text not null,
  file_window text,
  ingested_at timestamptz not null default now()
);
alter table public.stg_mp_packages_intransit enable row level security;
drop policy if exists stg_mp_packages_intransit_read on public.stg_mp_packages_intransit;
create policy stg_mp_packages_intransit_read on public.stg_mp_packages_intransit for select to authenticated using (true);
insert into public.stg_mp_packages_intransit (tag,source_file,file_sha256,licence,file_window) values
('1A40A030000E5B1000006219','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006220','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006221','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006222','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006576','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000010009','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014516','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014517','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014518','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014519','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014520','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014521','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014522','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014523','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014524','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006566','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006568','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006569','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006570','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006572','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006573','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006574','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000005373','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000005374','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000005375','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000005376','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000005377','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000005378','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014463','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014464','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014465','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014466','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014468','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014469','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014470','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014476','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014477','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014478','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014479','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014480','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014481','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014482','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014483','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014484','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014485','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014486','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014487','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014488','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014489','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014490','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014491','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014492','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014493','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014494','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014495','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014496','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014497','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014498','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014499','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014500','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014501','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014502','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014503','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014504','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014505','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014506','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014507','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014508','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014509','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014510','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014511','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014512','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014513','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014514','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000014515','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006558','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006559','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006560','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006561','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006562','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006563','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011953','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011954','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011955','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011956','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011957','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011958','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011974','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011984','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011985','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011986','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011987','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011988','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011989','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011990','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011991','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011992','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011993','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011994','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011948','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011903','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011904','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011905','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011906','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011907','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011908','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011909','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011910','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011911','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011912','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011913','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011914','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011915','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011916','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011917','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011918','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011919','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011921','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011922','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011923','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011924','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011925','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006501','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006502','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B1000006503','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011680','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011681','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011682','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011690','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011691','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011692','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011693','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011694','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011263','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011264','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011265','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011269','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011291','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011292','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011293','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null),
('1A40A030000E5B2000011299','Metrc-Massachusetts-MP281909-Packages-InTransit.xlsx','1aaed63c197ab77038f88dd720005d85e551becdc876ac9df3d85e751886ceaf','MP281909',null);
