insert into public.nav_registry
  (category, category_order, label, item_order, icon, view_key, table_ref,
   description, enabled, color, admin_only, surface, subcategory, page_kind,
   date_policy, default_range, range_kind)
values
 ('Human Resources',7,'Pay Runs',20,'dollar','pay_runs','pay_runs',
  'Payroll batches. Draft, review, approve, pay. An approved run is never edited — a correction is a new run, so the history stays true.',
  true,'#e2bd63',true,'hr','Payroll & Budget','report','auto','this_month_td','activity'),
 ('Human Resources',7,'Pay Run Detail',21,'clip','pay_run_lines','pay_run_lines',
  'Every earning and deduction, per person, per run — carrying the department and the 280E cost class so the tax split is a fact of the record.',
  true,'#e2bd63',true,'hr','Payroll & Budget','report','auto','this_month_td','activity'),
 ('Human Resources',7,'Payroll Journal (280E)',22,'dollar','payroll_journal','v_payroll_journal',
  'The journal a run posts to QuickBooks, already split by 280E class — deductible production labour separated from disallowed selling and administrative labour.',
  true,'#ff4245',true,'hr','Payroll & Budget','report','auto','this_month_td','activity'),
 ('Human Resources',7,'Year to Date',23,'chart','payroll_ytd','v_payroll_ytd',
  'Gross, taxable, deductions, net and hours per person per tax year. The basis of a pay stub and of W-2 preparation.',
  true,'#e2bd63',true,'hr','Payroll & Budget','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'Earning Codes',24,'clip','earning_codes','earning_codes',
  'Regular, overtime, holiday, PTO, bonus, retro. Multiplier, taxability, whether it counts toward overtime, its GL account and its 280E class — all editable.',
  true,'#2df26a',false,'hr','Payroll & Budget','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'Deduction Codes',25,'clip','deduction_codes','deduction_codes',
  'Pre-tax, post-tax, garnishments and employer contributions including Massachusetts PFML. Amount or percentage, with annual caps.',
  true,'#2df26a',false,'hr','Payroll & Budget','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'Tax Profiles',26,'shield','tax_profiles','employee_tax_profile',
  'W-4 and Massachusetts M-4 per person — filing status, dependants, extra withholding, exemptions.',
  true,'#57a9ff',true,'hr','Payroll & Budget','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'Time Off Requests',27,'calendar','time_off_requests','time_off_requests',
  'PTO, sick and unpaid leave requests with their approval trail.',
  true,'#2df26a',false,'hr','Time Off','report','auto','this_month_td','activity'),
 ('Human Resources',7,'PTO Balances',28,'calendar','employee_pto','employee_pto',
  'Current balance, accrued and used year to date, per person per policy.',
  true,'#2df26a',false,'hr','Time Off','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'PTO Ledger',29,'clip','pto_ledger','pto_ledger',
  'Every movement of every balance, forever. A balance you cannot explain line by line is a balance you cannot defend in a wage claim.',
  true,'#57a9ff',false,'hr','Time Off','report','auto','this_month_td','activity'),
 ('Human Resources',7,'Leave Policies',30,'clip','pto_policies','pto_policies',
  'Accrual method, rate, annual cap and carryover. Massachusetts earned sick time is one hour per thirty worked, capped at forty — expressed as rows, not code.',
  true,'#2df26a',false,'hr','Time Off','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'Holidays',31,'calendar','holidays','holidays',
  'The holiday calendar, whether each is paid, and the multiplier when it is worked.',
  true,'#2df26a',false,'hr','Time Off','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'QuickBooks Accounts',32,'dollar','qbo_account_map','qbo_account_map',
  'Which QuickBooks account each kind of payroll cost posts to, split by 280E class.',
  true,'#57a9ff',true,'hr','Integrations','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'QuickBooks Employee Map',33,'people','qbo_employee_map','qbo_employee_map',
  'Links each person to their QuickBooks record and to the payroll company''s own id. Without it an export is guessing at who is who.',
  true,'#57a9ff',true,'hr','Integrations','report','not_applicable',null,'snapshot'),
 ('Human Resources',7,'Payroll Imports',34,'upload','payroll_imports','payroll_imports',
  'Payroll reports uploaded back from the provider and reconciled against the roster. rows_unmatched is the number that matters.',
  true,'#e2bd63',true,'hr','Integrations','report','auto','this_month_td','activity'),
 ('Human Resources',7,'Cost Classes (280E)',35,'shield','cost_classes','cost_classes',
  'How each department''s labour is treated for 280E. Direct and indirect production are inventoriable COGS; selling and administrative are disallowed.',
  true,'#ff4245',false,'hr','Payroll & Budget','report','not_applicable',null,'snapshot')
on conflict do nothing;

select count(*) as hr_pages from public.nav_registry where enabled and surface='hr';;
