-- METRC EXPORT DROP, 26 AUGUST 2026 - STAGED, NOT TYPED.
--
-- NOT APPLIED. Branch only, held for APPLY.
--
-- Generated by tools/ingest/build_metrc_aug26.py directly from the files in
-- Downloads. Nothing here was retyped by hand: 14,168 transferred package lines and
-- 53,012 inactive plants do not survive transcription, and this session already put
-- one stray character into a deployed edge function that way.
--
-- EACH FILE LANDS IN ITS OWN STAGING TABLE WHOSE COLUMNS ARE THE FILE'S OWN HEADER,
-- ALL TEXT. That is deliberate. Typing a column guesses at a meaning nobody has
-- reviewed, and a wrong guess repeated 14,168 times is far more expensive than a
-- later, reviewed mapping step. Every row carries source_file, file_sha256, licence
-- and the report window, so any figure can be traced back to the bytes it came from.
--
-- WHAT IS NOT HERE, BY INSTRUCTION:
--   * metrc_rpt_point_in_time is untouched, and no 2024-12-31 or 2025-12-31 close is
--     loaded. Agent A owns PIT and the licence-in-key change.
--   * PackagesInventoryReport (4)(5)(6) are SNAPSHOTS, never on-hand. They are staged
--     with their own window and must not be upserted into live quantity or used as
--     Packages Active. On-hand for MP281909 is Packages-Active (507) and nothing else.
--   * Shipped and received quantities are stored as they appear and are never netted.
--   * Adjustment quantities keep Metrc's sign.
--   * The two incoming transfer rows stay unreceived - no received_at is invented.
--   * IL* destinations on transferred packages are lab submits, not sales. Nothing
--     here classifies them; the raw destination licence is preserved for the mapping
--     step to judge.
--
-- COUNT GATE: a file whose parsed rows missed its expected count by more than 1%
-- emitted nothing at all. See the run report in the PR body for what passed.

-- ── stg_mc_plantings_active: 57 rows ──────────────────────────────
create table if not exists public.stg_mc_plantings_active (
  plant_batch text,
  source_file text not null,
  file_sha256 text not null,
  licence text not null,
  file_window text,
  ingested_at timestamptz not null default now()
);
alter table public.stg_mc_plantings_active enable row level security;
drop policy if exists stg_mc_plantings_active_read on public.stg_mc_plantings_active;
create policy stg_mc_plantings_active_read on public.stg_mc_plantings_active for select to authenticated using (true);
insert into public.stg_mc_plantings_active (plant_batch,source_file,file_sha256,licence,file_window) values
('TG Shake Shack - 20260817','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Blueberry Muffin #4 - 20260814','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260814','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG LMNT 115 #5 - 20260814','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Blueberry Muffin #4 - 20260813','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Blueberry Muffin #4 - 20260813 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Blueberry Muffin #4 - 20260813 - B','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Blueberry Muffin #4 - 20260813 - C','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Blueberry Muffin #4 - 20260813 - D','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Cap Junky - 20260813','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Cap Junky - 20260813 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Cap Junky - 20260813 - B','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260804 - J','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813 - B','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813 - C','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813 - D','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813 - E','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813 - F','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813 - G','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260813 - H','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Lemon Drop - 20260804 - E','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG LMNT 115 #5 - 20260813','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG LMNT 115 #5 - 20260813 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG LMNT 115 #5 - 20260813 - B','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG LMNT 115 #5 - 20260813 - C','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Satsuma Sherbet - 20260804 - H','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Strawberry Biscotti - 20260804 - E','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Super Boof - 20260804 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Apple Fritter - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Blue Dream - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Blueberry Muffin #4 - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Cherry Lime Runtz - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Chimera - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Dirty Taxi - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260804 - E','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260804 - G','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Gush Mintz - 20260804 - H','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Lemon Drop - 20260804 - D','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG LMNT 115 #5 - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG LMNT 115 #5 - 20260804 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG LMNT 115 #5 - 20260804 - B','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG MAC 1 - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG MAC 1 - 20260804 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG MAC 1 - 20260804 - B','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Moroccan Peaches - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Orange Cream - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Satsuma Sherbet - 20260804 - D','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Satsuma Sherbet - 20260804 - E','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Spec Ops - 20260804 - C','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Splash - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Strawberry Biscotti - 20260804 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG Strawberry Biscotti - 20260804 - B','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG XJ-13 - 20260804','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null),
('TG XJ-13 - 20260804 - A','Metrc-Massachusetts-MC281714-Plants-Plantings-Active (3).xlsx','9a28d687d6b0fa619b86170c735fc3c81801e308a4dca27fd97c2244211ee6af','MC281714',null);
